/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.ui.outline;

import java.util.function.Consumer;
import org.csstudio.xtext.dbtexteditor.dbTextEditor.Field;
import org.csstudio.xtext.dbtexteditor.dbTextEditor.Record;
import org.csstudio.xtext.dbtexteditor.dbTextEditor.dbModel;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class DbTextEditorOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Field f) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final dbModel dbmodel) {
    final Consumer<Record> _function = (Record recordname) -> {
      this.createNode(outlineNode, recordname);
    };
    dbmodel.getRecords().forEach(_function);
  }
}
