/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.validation

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DbTextEditorValidator extends AbstractDbTextEditorValidator {
	
	

//	public static val INVALID_NAME = 'invalidName'

//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					DbTextEditorPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	}