/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDbdTextEditorScopeProvider extends DelegatingScopeProvider {
}
