/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.parser.antlr;

import com.google.inject.Inject;
import org.csstudio.xtext.dbtexteditor.parser.antlr.internal.InternalDbTextEditorParser;
import org.csstudio.xtext.dbtexteditor.services.DbTextEditorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DbTextEditorParser extends AbstractAntlrParser {

	@Inject
	private DbTextEditorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDbTextEditorParser createParser(XtextTokenStream stream) {
		return new InternalDbTextEditorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "dbModel";
	}

	public DbTextEditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DbTextEditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
