/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDbTextEditorScopeProvider extends DelegatingScopeProvider {
}
