/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl;

import java.util.Collection;

import org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage;
import org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field;
import org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype;
import org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recordtype</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl#getRecordtypename <em>Recordtypename</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RecordtypeImpl extends MinimalEObjectImpl.Container implements Recordtype
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getRecordtypename() <em>Recordtypename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordtypename()
   * @generated
   * @ordered
   */
  protected static final Recordtypenames RECORDTYPENAME_EDEFAULT = Recordtypenames.CALCOUT;

  /**
   * The cached value of the '{@link #getRecordtypename() <em>Recordtypename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordtypename()
   * @generated
   * @ordered
   */
  protected Recordtypenames recordtypename = RECORDTYPENAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<Field> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecordtypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DbdTextEditorPackage.Literals.RECORDTYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DbdTextEditorPackage.RECORDTYPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Recordtypenames getRecordtypename()
  {
    return recordtypename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRecordtypename(Recordtypenames newRecordtypename)
  {
    Recordtypenames oldRecordtypename = recordtypename;
    recordtypename = newRecordtypename == null ? RECORDTYPENAME_EDEFAULT : newRecordtypename;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DbdTextEditorPackage.RECORDTYPE__RECORDTYPENAME, oldRecordtypename, recordtypename));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Field> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<Field>(Field.class, this, DbdTextEditorPackage.RECORDTYPE__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DbdTextEditorPackage.RECORDTYPE__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DbdTextEditorPackage.RECORDTYPE__NAME:
        return getName();
      case DbdTextEditorPackage.RECORDTYPE__RECORDTYPENAME:
        return getRecordtypename();
      case DbdTextEditorPackage.RECORDTYPE__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DbdTextEditorPackage.RECORDTYPE__NAME:
        setName((String)newValue);
        return;
      case DbdTextEditorPackage.RECORDTYPE__RECORDTYPENAME:
        setRecordtypename((Recordtypenames)newValue);
        return;
      case DbdTextEditorPackage.RECORDTYPE__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends Field>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DbdTextEditorPackage.RECORDTYPE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DbdTextEditorPackage.RECORDTYPE__RECORDTYPENAME:
        setRecordtypename(RECORDTYPENAME_EDEFAULT);
        return;
      case DbdTextEditorPackage.RECORDTYPE__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DbdTextEditorPackage.RECORDTYPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DbdTextEditorPackage.RECORDTYPE__RECORDTYPENAME:
        return recordtypename != RECORDTYPENAME_EDEFAULT;
      case DbdTextEditorPackage.RECORDTYPE__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", recordtypename: ");
    result.append(recordtypename);
    result.append(')');
    return result.toString();
  }

} //RecordtypeImpl
