/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.parser.antlr;

import com.google.inject.Inject;
import org.csstudio.xtext.dbdtexteditor.parser.antlr.internal.InternalDbdTextEditorParser;
import org.csstudio.xtext.dbdtexteditor.services.DbdTextEditorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DbdTextEditorParser extends AbstractAntlrParser {

	@Inject
	private DbdTextEditorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDbdTextEditorParser createParser(XtextTokenStream stream) {
		return new InternalDbdTextEditorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "dbdModel";
	}

	public DbdTextEditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DbdTextEditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
