/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DbTextEditorRuntimeModule extends AbstractDbTextEditorRuntimeModule {
}
