/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ui.tests;

import com.google.inject.Injector;
import org.csstudio.xtext.dbdtexteditor.ui.internal.DbdtexteditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DbdTextEditorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DbdtexteditorActivator.getInstance().getInjector("org.csstudio.xtext.dbdtexteditor.DbdTextEditor");
	}

}
