/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ide


/**
 * Use this class to register ide components.
 */
class DbdTextEditorIdeModule extends AbstractDbdTextEditorIdeModule {
}
