/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.scoping;

import org.csstudio.xtext.dbdtexteditor.scoping.AbstractDbdTextEditorScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DbdTextEditorScopeProvider extends AbstractDbdTextEditorScopeProvider {
}
