/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicename <em>Choicename</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicestring <em>Choicestring</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getChoice()
 * @model
 * @generated
 */
public interface Choice extends EObject
{
  /**
   * Returns the value of the '<em><b>Choicename</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Choicename</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choicename</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames
   * @see #setChoicename(Choicenames)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getChoice_Choicename()
   * @model
   * @generated
   */
  Choicenames getChoicename();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicename <em>Choicename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choicename</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames
   * @see #getChoicename()
   * @generated
   */
  void setChoicename(Choicenames value);

  /**
   * Returns the value of the '<em><b>Choicestring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Choicestring</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choicestring</em>' attribute.
   * @see #setChoicestring(String)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getChoice_Choicestring()
   * @model
   * @generated
   */
  String getChoicestring();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicestring <em>Choicestring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choicestring</em>' attribute.
   * @see #getChoicestring()
   * @generated
   */
  void setChoicestring(String value);

} // Choice
