/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorFactory
 * @model kind="package"
 * @generated
 */
public interface DbdTextEditorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dbdTextEditor";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.csstudio.org/xtext/dbdtexteditor/DbdTextEditor";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dbdTextEditor";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DbdTextEditorPackage eINSTANCE = org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl.init();

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.dbdModelImpl <em>dbd Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.dbdModelImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getdbdModel()
   * @generated
   */
  int DBD_MODEL = 0;

  /**
   * The feature id for the '<em><b>Menus</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DBD_MODEL__MENUS = 0;

  /**
   * The feature id for the '<em><b>Recordtypes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DBD_MODEL__RECORDTYPES = 1;

  /**
   * The number of structural features of the '<em>dbd Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DBD_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.MenuImpl <em>Menu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.MenuImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getMenu()
   * @generated
   */
  int MENU = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__NAME = 0;

  /**
   * The feature id for the '<em><b>Menuname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__MENUNAME = 1;

  /**
   * The feature id for the '<em><b>Choices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__CHOICES = 2;

  /**
   * The number of structural features of the '<em>Menu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.ChoiceImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 2;

  /**
   * The feature id for the '<em><b>Choicename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__CHOICENAME = 0;

  /**
   * The feature id for the '<em><b>Choicestring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__CHOICESTRING = 1;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl <em>Recordtype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getRecordtype()
   * @generated
   */
  int RECORDTYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDTYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Recordtypename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDTYPE__RECORDTYPENAME = 1;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDTYPE__FIELDS = 2;

  /**
   * The number of structural features of the '<em>Recordtype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDTYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getField()
   * @generated
   */
  int FIELD = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Fieldname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__FIELDNAME = 1;

  /**
   * The feature id for the '<em><b>Dbf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__DBF = 2;

  /**
   * The feature id for the '<em><b>Fieldattributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__FIELDATTRIBUTES = 3;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldattributeImpl <em>Fieldattribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldattributeImpl
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldattribute()
   * @generated
   */
  int FIELDATTRIBUTE = 5;

  /**
   * The feature id for the '<em><b>Fieldattribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELDATTRIBUTE__FIELDATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Fieldattributestring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELDATTRIBUTE__FIELDATTRIBUTESTRING = 1;

  /**
   * The feature id for the '<em><b>Fieldattributeint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELDATTRIBUTE__FIELDATTRIBUTEINT = 2;

  /**
   * The number of structural features of the '<em>Fieldattribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELDATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames <em>Menunames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getMenunames()
   * @generated
   */
  int MENUNAMES = 6;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames <em>Choicenames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getChoicenames()
   * @generated
   */
  int CHOICENAMES = 7;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames <em>Recordtypenames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getRecordtypenames()
   * @generated
   */
  int RECORDTYPENAMES = 8;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames <em>Fieldnames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldnames()
   * @generated
   */
  int FIELDNAMES = 9;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames <em>Dbfnames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getDbfnames()
   * @generated
   */
  int DBFNAMES = 10;

  /**
   * The meta object id for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames <em>Fieldattributenames</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldattributenames()
   * @generated
   */
  int FIELDATTRIBUTENAMES = 11;


  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel <em>dbd Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>dbd Model</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel
   * @generated
   */
  EClass getdbdModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel#getMenus <em>Menus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menus</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel#getMenus()
   * @see #getdbdModel()
   * @generated
   */
  EReference getdbdModel_Menus();

  /**
   * Returns the meta object for the containment reference list '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel#getRecordtypes <em>Recordtypes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recordtypes</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.dbdModel#getRecordtypes()
   * @see #getdbdModel()
   * @generated
   */
  EReference getdbdModel_Recordtypes();

  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu <em>Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Menu</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu
   * @generated
   */
  EClass getMenu();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getName()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Name();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getMenuname <em>Menuname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Menuname</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getMenuname()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Menuname();

  /**
   * Returns the meta object for the containment reference list '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getChoices <em>Choices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choices</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getChoices()
   * @see #getMenu()
   * @generated
   */
  EReference getMenu_Choices();

  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicename <em>Choicename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choicename</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicename()
   * @see #getChoice()
   * @generated
   */
  EAttribute getChoice_Choicename();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicestring <em>Choicestring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choicestring</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice#getChoicestring()
   * @see #getChoice()
   * @generated
   */
  EAttribute getChoice_Choicestring();

  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype <em>Recordtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recordtype</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype
   * @generated
   */
  EClass getRecordtype();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getName()
   * @see #getRecordtype()
   * @generated
   */
  EAttribute getRecordtype_Name();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getRecordtypename <em>Recordtypename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Recordtypename</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getRecordtypename()
   * @see #getRecordtype()
   * @generated
   */
  EAttribute getRecordtype_Recordtypename();

  /**
   * Returns the meta object for the containment reference list '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getFields()
   * @see #getRecordtype()
   * @generated
   */
  EReference getRecordtype_Fields();

  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getFieldname <em>Fieldname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fieldname</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getFieldname()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Fieldname();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getDbf <em>Dbf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dbf</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getDbf()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Dbf();

  /**
   * Returns the meta object for the containment reference list '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getFieldattributes <em>Fieldattributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fieldattributes</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field#getFieldattributes()
   * @see #getField()
   * @generated
   */
  EReference getField_Fieldattributes();

  /**
   * Returns the meta object for class '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute <em>Fieldattribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fieldattribute</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute
   * @generated
   */
  EClass getFieldattribute();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattribute <em>Fieldattribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fieldattribute</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattribute()
   * @see #getFieldattribute()
   * @generated
   */
  EAttribute getFieldattribute_Fieldattribute();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributestring <em>Fieldattributestring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fieldattributestring</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributestring()
   * @see #getFieldattribute()
   * @generated
   */
  EAttribute getFieldattribute_Fieldattributestring();

  /**
   * Returns the meta object for the attribute '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributeint <em>Fieldattributeint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fieldattributeint</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributeint()
   * @see #getFieldattribute()
   * @generated
   */
  EAttribute getFieldattribute_Fieldattributeint();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames <em>Menunames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Menunames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames
   * @generated
   */
  EEnum getMenunames();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames <em>Choicenames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Choicenames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames
   * @generated
   */
  EEnum getChoicenames();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames <em>Recordtypenames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Recordtypenames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames
   * @generated
   */
  EEnum getRecordtypenames();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames <em>Fieldnames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Fieldnames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames
   * @generated
   */
  EEnum getFieldnames();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames <em>Dbfnames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Dbfnames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames
   * @generated
   */
  EEnum getDbfnames();

  /**
   * Returns the meta object for enum '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames <em>Fieldattributenames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Fieldattributenames</em>'.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames
   * @generated
   */
  EEnum getFieldattributenames();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DbdTextEditorFactory getDbdTextEditorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.dbdModelImpl <em>dbd Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.dbdModelImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getdbdModel()
     * @generated
     */
    EClass DBD_MODEL = eINSTANCE.getdbdModel();

    /**
     * The meta object literal for the '<em><b>Menus</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DBD_MODEL__MENUS = eINSTANCE.getdbdModel_Menus();

    /**
     * The meta object literal for the '<em><b>Recordtypes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DBD_MODEL__RECORDTYPES = eINSTANCE.getdbdModel_Recordtypes();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.MenuImpl <em>Menu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.MenuImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getMenu()
     * @generated
     */
    EClass MENU = eINSTANCE.getMenu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__NAME = eINSTANCE.getMenu_Name();

    /**
     * The meta object literal for the '<em><b>Menuname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__MENUNAME = eINSTANCE.getMenu_Menuname();

    /**
     * The meta object literal for the '<em><b>Choices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENU__CHOICES = eINSTANCE.getMenu_Choices();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.ChoiceImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '<em><b>Choicename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE__CHOICENAME = eINSTANCE.getChoice_Choicename();

    /**
     * The meta object literal for the '<em><b>Choicestring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE__CHOICESTRING = eINSTANCE.getChoice_Choicestring();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl <em>Recordtype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.RecordtypeImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getRecordtype()
     * @generated
     */
    EClass RECORDTYPE = eINSTANCE.getRecordtype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORDTYPE__NAME = eINSTANCE.getRecordtype_Name();

    /**
     * The meta object literal for the '<em><b>Recordtypename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORDTYPE__RECORDTYPENAME = eINSTANCE.getRecordtype_Recordtypename();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECORDTYPE__FIELDS = eINSTANCE.getRecordtype_Fields();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Fieldname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__FIELDNAME = eINSTANCE.getField_Fieldname();

    /**
     * The meta object literal for the '<em><b>Dbf</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__DBF = eINSTANCE.getField_Dbf();

    /**
     * The meta object literal for the '<em><b>Fieldattributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__FIELDATTRIBUTES = eINSTANCE.getField_Fieldattributes();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldattributeImpl <em>Fieldattribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.FieldattributeImpl
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldattribute()
     * @generated
     */
    EClass FIELDATTRIBUTE = eINSTANCE.getFieldattribute();

    /**
     * The meta object literal for the '<em><b>Fieldattribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELDATTRIBUTE__FIELDATTRIBUTE = eINSTANCE.getFieldattribute_Fieldattribute();

    /**
     * The meta object literal for the '<em><b>Fieldattributestring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELDATTRIBUTE__FIELDATTRIBUTESTRING = eINSTANCE.getFieldattribute_Fieldattributestring();

    /**
     * The meta object literal for the '<em><b>Fieldattributeint</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELDATTRIBUTE__FIELDATTRIBUTEINT = eINSTANCE.getFieldattribute_Fieldattributeint();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames <em>Menunames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getMenunames()
     * @generated
     */
    EEnum MENUNAMES = eINSTANCE.getMenunames();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames <em>Choicenames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choicenames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getChoicenames()
     * @generated
     */
    EEnum CHOICENAMES = eINSTANCE.getChoicenames();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames <em>Recordtypenames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getRecordtypenames()
     * @generated
     */
    EEnum RECORDTYPENAMES = eINSTANCE.getRecordtypenames();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames <em>Fieldnames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldnames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldnames()
     * @generated
     */
    EEnum FIELDNAMES = eINSTANCE.getFieldnames();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames <em>Dbfnames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Dbfnames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getDbfnames()
     * @generated
     */
    EEnum DBFNAMES = eINSTANCE.getDbfnames();

    /**
     * The meta object literal for the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames <em>Fieldattributenames</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames
     * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.impl.DbdTextEditorPackageImpl#getFieldattributenames()
     * @generated
     */
    EEnum FIELDATTRIBUTENAMES = eINSTANCE.getFieldattributenames();

  }

} //DbdTextEditorPackage
