/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fieldattribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattribute <em>Fieldattribute</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributestring <em>Fieldattributestring</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributeint <em>Fieldattributeint</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getFieldattribute()
 * @model
 * @generated
 */
public interface Fieldattribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Fieldattribute</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldattribute</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldattribute</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames
   * @see #setFieldattribute(Fieldattributenames)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getFieldattribute_Fieldattribute()
   * @model
   * @generated
   */
  Fieldattributenames getFieldattribute();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattribute <em>Fieldattribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldattribute</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattributenames
   * @see #getFieldattribute()
   * @generated
   */
  void setFieldattribute(Fieldattributenames value);

  /**
   * Returns the value of the '<em><b>Fieldattributestring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldattributestring</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldattributestring</em>' attribute.
   * @see #setFieldattributestring(String)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getFieldattribute_Fieldattributestring()
   * @model
   * @generated
   */
  String getFieldattributestring();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributestring <em>Fieldattributestring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldattributestring</em>' attribute.
   * @see #getFieldattributestring()
   * @generated
   */
  void setFieldattributestring(String value);

  /**
   * Returns the value of the '<em><b>Fieldattributeint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldattributeint</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldattributeint</em>' attribute.
   * @see #setFieldattributeint(int)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getFieldattribute_Fieldattributeint()
   * @model
   * @generated
   */
  int getFieldattributeint();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Fieldattribute#getFieldattributeint <em>Fieldattributeint</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldattributeint</em>' attribute.
   * @see #getFieldattributeint()
   * @generated
   */
  void setFieldattributeint(int value);

} // Fieldattribute
