/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Menunames</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getMenunames()
 * @model
 * @generated
 */
public enum Menunames implements Enumerator
{
  /**
   * The '<em><b>Serial PRTY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_PRTY_VALUE
   * @generated
   * @ordered
   */
  SERIAL_PRTY(0, "serialPRTY", "serialPRTY"),

  /**
   * The '<em><b>Waveform POST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WAVEFORM_POST_VALUE
   * @generated
   * @ordered
   */
  WAVEFORM_POST(1, "waveformPOST", "waveformPOST"),

  /**
   * The '<em><b>Aao POST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AAO_POST_VALUE
   * @generated
   * @ordered
   */
  AAO_POST(2, "aaoPOST", "aaoPOST"),

  /**
   * The '<em><b>Menu Priority</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_PRIORITY_VALUE
   * @generated
   * @ordered
   */
  MENU_PRIORITY(3, "menuPriority", "menuPriority"),

  /**
   * The '<em><b>Serial SBIT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_SBIT_VALUE
   * @generated
   * @ordered
   */
  SERIAL_SBIT(4, "serialSBIT", "serialSBIT"),

  /**
   * The '<em><b>Calcout DOPT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALCOUT_DOPT_VALUE
   * @generated
   * @ordered
   */
  CALCOUT_DOPT(5, "calcoutDOPT", "calcoutDOPT"),

  /**
   * The '<em><b>SDIS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SDIS_VALUE
   * @generated
   * @ordered
   */
  SDIS(6, "SDIS", "SDIS"),

  /**
   * The '<em><b>Menu Omsl</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_OMSL_VALUE
   * @generated
   * @ordered
   */
  MENU_OMSL(7, "menuOmsl", "menuOmsl"),

  /**
   * The '<em><b>Menu Ftype</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_FTYPE_VALUE
   * @generated
   * @ordered
   */
  MENU_FTYPE(8, "menuFtype", "menuFtype"),

  /**
   * The '<em><b>Stringin POST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STRINGIN_POST_VALUE
   * @generated
   * @ordered
   */
  STRINGIN_POST(9, "stringinPOST", "stringinPOST"),

  /**
   * The '<em><b>Menu Pini</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_PINI_VALUE
   * @generated
   * @ordered
   */
  MENU_PINI(10, "menuPini", "menuPini"),

  /**
   * The '<em><b>Dfanout SELM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DFANOUT_SELM_VALUE
   * @generated
   * @ordered
   */
  DFANOUT_SELM(11, "dfanoutSELM", "dfanoutSELM"),

  /**
   * The '<em><b>Menu Scan</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_SCAN_VALUE
   * @generated
   * @ordered
   */
  MENU_SCAN(12, "menuScan", "menuScan"),

  /**
   * The '<em><b>Gpib ACMD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GPIB_ACMD_VALUE
   * @generated
   * @ordered
   */
  GPIB_ACMD(13, "gpibACMD", "gpibACMD"),

  /**
   * The '<em><b>ASub LFLG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASUB_LFLG_VALUE
   * @generated
   * @ordered
   */
  ASUB_LFLG(14, "aSubLFLG", "aSubLFLG"),

  /**
   * The '<em><b>Asyn TMOD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_TMOD_VALUE
   * @generated
   * @ordered
   */
  ASYN_TMOD(15, "asynTMOD", "asynTMOD"),

  /**
   * The '<em><b>Scaler D1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCALER_D1_VALUE
   * @generated
   * @ordered
   */
  SCALER_D1(16, "scalerD1", "scalerD1"),

  /**
   * The '<em><b>Menu Post</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_POST_VALUE
   * @generated
   * @ordered
   */
  MENU_POST(17, "menuPost", "menuPost"),

  /**
   * The '<em><b>Asyn INTERFACE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_INTERFACE_VALUE
   * @generated
   * @ordered
   */
  ASYN_INTERFACE(18, "asynINTERFACE", "asynINTERFACE"),

  /**
   * The '<em><b>Menu Alarm Stat</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_ALARM_STAT_VALUE
   * @generated
   * @ordered
   */
  MENU_ALARM_STAT(19, "menuAlarmStat", "menuAlarmStat"),

  /**
   * The '<em><b>Ao OIF</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AO_OIF_VALUE
   * @generated
   * @ordered
   */
  AO_OIF(20, "aoOIF", "aoOIF"),

  /**
   * The '<em><b>Buffering ALG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUFFERING_ALG_VALUE
   * @generated
   * @ordered
   */
  BUFFERING_ALG(21, "bufferingALG", "bufferingALG"),

  /**
   * The '<em><b>Aai POST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AAI_POST_VALUE
   * @generated
   * @ordered
   */
  AAI_POST(22, "aaiPOST", "aaiPOST"),

  /**
   * The '<em><b>Epid Feedback State</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EPID_FEEDBACK_STATE_VALUE
   * @generated
   * @ordered
   */
  EPID_FEEDBACK_STATE(23, "epidFeedbackState", "epidFeedbackState"),

  /**
   * The '<em><b>Calcout INAV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALCOUT_INAV_VALUE
   * @generated
   * @ordered
   */
  CALCOUT_INAV(24, "calcoutINAV", "calcoutINAV"),

  /**
   * The '<em><b>Asyn AUTOCONNECT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_AUTOCONNECT_VALUE
   * @generated
   * @ordered
   */
  ASYN_AUTOCONNECT(25, "asynAUTOCONNECT", "asynAUTOCONNECT"),

  /**
   * The '<em><b>Asyn FMT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_FMT_VALUE
   * @generated
   * @ordered
   */
  ASYN_FMT(26, "asynFMT", "asynFMT"),

  /**
   * The '<em><b>Asyn CONNECT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_CONNECT_VALUE
   * @generated
   * @ordered
   */
  ASYN_CONNECT(27, "asynCONNECT", "asynCONNECT"),

  /**
   * The '<em><b>Gpib UCMD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GPIB_UCMD_VALUE
   * @generated
   * @ordered
   */
  GPIB_UCMD(28, "gpibUCMD", "gpibUCMD"),

  /**
   * The '<em><b>Serial BAUD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_BAUD_VALUE
   * @generated
   * @ordered
   */
  SERIAL_BAUD(29, "serialBAUD", "serialBAUD"),

  /**
   * The '<em><b>Histogram CMD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HISTOGRAM_CMD_VALUE
   * @generated
   * @ordered
   */
  HISTOGRAM_CMD(30, "histogramCMD", "histogramCMD"),

  /**
   * The '<em><b>Asyn TRACE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_TRACE_VALUE
   * @generated
   * @ordered
   */
  ASYN_TRACE(31, "asynTRACE", "asynTRACE"),

  /**
   * The '<em><b>Scaler G1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCALER_G1_VALUE
   * @generated
   * @ordered
   */
  SCALER_G1(32, "scalerG1", "scalerG1"),

  /**
   * The '<em><b>Asyn EOMREASON</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_EOMREASON_VALUE
   * @generated
   * @ordered
   */
  ASYN_EOMREASON(33, "asynEOMREASON", "asynEOMREASON"),

  /**
   * The '<em><b>Scaler CONT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCALER_CONT_VALUE
   * @generated
   * @ordered
   */
  SCALER_CONT(34, "scalerCONT", "scalerCONT"),

  /**
   * The '<em><b>Menu Ivoa</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_IVOA_VALUE
   * @generated
   * @ordered
   */
  MENU_IVOA(35, "menuIvoa", "menuIvoa"),

  /**
   * The '<em><b>Stringout POST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STRINGOUT_POST_VALUE
   * @generated
   * @ordered
   */
  STRINGOUT_POST(36, "stringoutPOST", "stringoutPOST"),

  /**
   * The '<em><b>Menu Alarm Sevr</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_ALARM_SEVR_VALUE
   * @generated
   * @ordered
   */
  MENU_ALARM_SEVR(37, "menuAlarmSevr", "menuAlarmSevr"),

  /**
   * The '<em><b>Serial MCTL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_MCTL_VALUE
   * @generated
   * @ordered
   */
  SERIAL_MCTL(38, "serialMCTL", "serialMCTL"),

  /**
   * The '<em><b>Serial FCTL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_FCTL_VALUE
   * @generated
   * @ordered
   */
  SERIAL_FCTL(39, "serialFCTL", "serialFCTL"),

  /**
   * The '<em><b>Menu Simm</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_SIMM_VALUE
   * @generated
   * @ordered
   */
  MENU_SIMM(40, "menuSimm", "menuSimm"),

  /**
   * The '<em><b>Compress ALG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMPRESS_ALG_VALUE
   * @generated
   * @ordered
   */
  COMPRESS_ALG(41, "compressALG", "compressALG"),

  /**
   * The '<em><b>ASub EFLG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASUB_EFLG_VALUE
   * @generated
   * @ordered
   */
  ASUB_EFLG(42, "aSubEFLG", "aSubEFLG"),

  /**
   * The '<em><b>Fanout SELM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FANOUT_SELM_VALUE
   * @generated
   * @ordered
   */
  FANOUT_SELM(43, "fanoutSELM", "fanoutSELM"),

  /**
   * The '<em><b>Calcout OOPT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALCOUT_OOPT_VALUE
   * @generated
   * @ordered
   */
  CALCOUT_OOPT(44, "calcoutOOPT", "calcoutOOPT"),

  /**
   * The '<em><b>Asyn ENABLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASYN_ENABLE_VALUE
   * @generated
   * @ordered
   */
  ASYN_ENABLE(45, "asynENABLE", "asynENABLE"),

  /**
   * The '<em><b>Epid Feedback Mode</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EPID_FEEDBACK_MODE_VALUE
   * @generated
   * @ordered
   */
  EPID_FEEDBACK_MODE(46, "epidFeedbackMode", "epidFeedbackMode"),

  /**
   * The '<em><b>Menu Convert</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_CONVERT_VALUE
   * @generated
   * @ordered
   */
  MENU_CONVERT(47, "menuConvert", "menuConvert"),

  /**
   * The '<em><b>Scaler CNT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCALER_CNT_VALUE
   * @generated
   * @ordered
   */
  SCALER_CNT(48, "scalerCNT", "scalerCNT"),

  /**
   * The '<em><b>Serial IX</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_IX_VALUE
   * @generated
   * @ordered
   */
  SERIAL_IX(49, "serialIX", "serialIX"),

  /**
   * The '<em><b>Menu Yes No</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_YES_NO_VALUE
   * @generated
   * @ordered
   */
  MENU_YES_NO(50, "menuYesNo", "menuYesNo"),

  /**
   * The '<em><b>Timestamp TST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TIMESTAMP_TST_VALUE
   * @generated
   * @ordered
   */
  TIMESTAMP_TST(51, "timestampTST", "timestampTST"),

  /**
   * The '<em><b>Serial DBIT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERIAL_DBIT_VALUE
   * @generated
   * @ordered
   */
  SERIAL_DBIT(52, "serialDBIT", "serialDBIT"),

  /**
   * The '<em><b>Sel SELM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEL_SELM_VALUE
   * @generated
   * @ordered
   */
  SEL_SELM(53, "selSELM", "selSELM");

  /**
   * The '<em><b>Serial PRTY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial PRTY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_PRTY
   * @model name="serialPRTY"
   * @generated
   * @ordered
   */
  public static final int SERIAL_PRTY_VALUE = 0;

  /**
   * The '<em><b>Waveform POST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Waveform POST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WAVEFORM_POST
   * @model name="waveformPOST"
   * @generated
   * @ordered
   */
  public static final int WAVEFORM_POST_VALUE = 1;

  /**
   * The '<em><b>Aao POST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Aao POST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AAO_POST
   * @model name="aaoPOST"
   * @generated
   * @ordered
   */
  public static final int AAO_POST_VALUE = 2;

  /**
   * The '<em><b>Menu Priority</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Priority</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_PRIORITY
   * @model name="menuPriority"
   * @generated
   * @ordered
   */
  public static final int MENU_PRIORITY_VALUE = 3;

  /**
   * The '<em><b>Serial SBIT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial SBIT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_SBIT
   * @model name="serialSBIT"
   * @generated
   * @ordered
   */
  public static final int SERIAL_SBIT_VALUE = 4;

  /**
   * The '<em><b>Calcout DOPT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Calcout DOPT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CALCOUT_DOPT
   * @model name="calcoutDOPT"
   * @generated
   * @ordered
   */
  public static final int CALCOUT_DOPT_VALUE = 5;

  /**
   * The '<em><b>SDIS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SDIS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SDIS
   * @model
   * @generated
   * @ordered
   */
  public static final int SDIS_VALUE = 6;

  /**
   * The '<em><b>Menu Omsl</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Omsl</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_OMSL
   * @model name="menuOmsl"
   * @generated
   * @ordered
   */
  public static final int MENU_OMSL_VALUE = 7;

  /**
   * The '<em><b>Menu Ftype</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Ftype</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_FTYPE
   * @model name="menuFtype"
   * @generated
   * @ordered
   */
  public static final int MENU_FTYPE_VALUE = 8;

  /**
   * The '<em><b>Stringin POST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Stringin POST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STRINGIN_POST
   * @model name="stringinPOST"
   * @generated
   * @ordered
   */
  public static final int STRINGIN_POST_VALUE = 9;

  /**
   * The '<em><b>Menu Pini</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Pini</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_PINI
   * @model name="menuPini"
   * @generated
   * @ordered
   */
  public static final int MENU_PINI_VALUE = 10;

  /**
   * The '<em><b>Dfanout SELM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Dfanout SELM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DFANOUT_SELM
   * @model name="dfanoutSELM"
   * @generated
   * @ordered
   */
  public static final int DFANOUT_SELM_VALUE = 11;

  /**
   * The '<em><b>Menu Scan</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Scan</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_SCAN
   * @model name="menuScan"
   * @generated
   * @ordered
   */
  public static final int MENU_SCAN_VALUE = 12;

  /**
   * The '<em><b>Gpib ACMD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Gpib ACMD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GPIB_ACMD
   * @model name="gpibACMD"
   * @generated
   * @ordered
   */
  public static final int GPIB_ACMD_VALUE = 13;

  /**
   * The '<em><b>ASub LFLG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ASub LFLG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASUB_LFLG
   * @model name="aSubLFLG"
   * @generated
   * @ordered
   */
  public static final int ASUB_LFLG_VALUE = 14;

  /**
   * The '<em><b>Asyn TMOD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn TMOD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_TMOD
   * @model name="asynTMOD"
   * @generated
   * @ordered
   */
  public static final int ASYN_TMOD_VALUE = 15;

  /**
   * The '<em><b>Scaler D1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Scaler D1</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCALER_D1
   * @model name="scalerD1"
   * @generated
   * @ordered
   */
  public static final int SCALER_D1_VALUE = 16;

  /**
   * The '<em><b>Menu Post</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Post</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_POST
   * @model name="menuPost"
   * @generated
   * @ordered
   */
  public static final int MENU_POST_VALUE = 17;

  /**
   * The '<em><b>Asyn INTERFACE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn INTERFACE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_INTERFACE
   * @model name="asynINTERFACE"
   * @generated
   * @ordered
   */
  public static final int ASYN_INTERFACE_VALUE = 18;

  /**
   * The '<em><b>Menu Alarm Stat</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Alarm Stat</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_ALARM_STAT
   * @model name="menuAlarmStat"
   * @generated
   * @ordered
   */
  public static final int MENU_ALARM_STAT_VALUE = 19;

  /**
   * The '<em><b>Ao OIF</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Ao OIF</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AO_OIF
   * @model name="aoOIF"
   * @generated
   * @ordered
   */
  public static final int AO_OIF_VALUE = 20;

  /**
   * The '<em><b>Buffering ALG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Buffering ALG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BUFFERING_ALG
   * @model name="bufferingALG"
   * @generated
   * @ordered
   */
  public static final int BUFFERING_ALG_VALUE = 21;

  /**
   * The '<em><b>Aai POST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Aai POST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AAI_POST
   * @model name="aaiPOST"
   * @generated
   * @ordered
   */
  public static final int AAI_POST_VALUE = 22;

  /**
   * The '<em><b>Epid Feedback State</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Epid Feedback State</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EPID_FEEDBACK_STATE
   * @model name="epidFeedbackState"
   * @generated
   * @ordered
   */
  public static final int EPID_FEEDBACK_STATE_VALUE = 23;

  /**
   * The '<em><b>Calcout INAV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Calcout INAV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CALCOUT_INAV
   * @model name="calcoutINAV"
   * @generated
   * @ordered
   */
  public static final int CALCOUT_INAV_VALUE = 24;

  /**
   * The '<em><b>Asyn AUTOCONNECT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn AUTOCONNECT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_AUTOCONNECT
   * @model name="asynAUTOCONNECT"
   * @generated
   * @ordered
   */
  public static final int ASYN_AUTOCONNECT_VALUE = 25;

  /**
   * The '<em><b>Asyn FMT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn FMT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_FMT
   * @model name="asynFMT"
   * @generated
   * @ordered
   */
  public static final int ASYN_FMT_VALUE = 26;

  /**
   * The '<em><b>Asyn CONNECT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn CONNECT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_CONNECT
   * @model name="asynCONNECT"
   * @generated
   * @ordered
   */
  public static final int ASYN_CONNECT_VALUE = 27;

  /**
   * The '<em><b>Gpib UCMD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Gpib UCMD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GPIB_UCMD
   * @model name="gpibUCMD"
   * @generated
   * @ordered
   */
  public static final int GPIB_UCMD_VALUE = 28;

  /**
   * The '<em><b>Serial BAUD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial BAUD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_BAUD
   * @model name="serialBAUD"
   * @generated
   * @ordered
   */
  public static final int SERIAL_BAUD_VALUE = 29;

  /**
   * The '<em><b>Histogram CMD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Histogram CMD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HISTOGRAM_CMD
   * @model name="histogramCMD"
   * @generated
   * @ordered
   */
  public static final int HISTOGRAM_CMD_VALUE = 30;

  /**
   * The '<em><b>Asyn TRACE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn TRACE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_TRACE
   * @model name="asynTRACE"
   * @generated
   * @ordered
   */
  public static final int ASYN_TRACE_VALUE = 31;

  /**
   * The '<em><b>Scaler G1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Scaler G1</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCALER_G1
   * @model name="scalerG1"
   * @generated
   * @ordered
   */
  public static final int SCALER_G1_VALUE = 32;

  /**
   * The '<em><b>Asyn EOMREASON</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn EOMREASON</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_EOMREASON
   * @model name="asynEOMREASON"
   * @generated
   * @ordered
   */
  public static final int ASYN_EOMREASON_VALUE = 33;

  /**
   * The '<em><b>Scaler CONT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Scaler CONT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCALER_CONT
   * @model name="scalerCONT"
   * @generated
   * @ordered
   */
  public static final int SCALER_CONT_VALUE = 34;

  /**
   * The '<em><b>Menu Ivoa</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Ivoa</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_IVOA
   * @model name="menuIvoa"
   * @generated
   * @ordered
   */
  public static final int MENU_IVOA_VALUE = 35;

  /**
   * The '<em><b>Stringout POST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Stringout POST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STRINGOUT_POST
   * @model name="stringoutPOST"
   * @generated
   * @ordered
   */
  public static final int STRINGOUT_POST_VALUE = 36;

  /**
   * The '<em><b>Menu Alarm Sevr</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Alarm Sevr</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_ALARM_SEVR
   * @model name="menuAlarmSevr"
   * @generated
   * @ordered
   */
  public static final int MENU_ALARM_SEVR_VALUE = 37;

  /**
   * The '<em><b>Serial MCTL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial MCTL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_MCTL
   * @model name="serialMCTL"
   * @generated
   * @ordered
   */
  public static final int SERIAL_MCTL_VALUE = 38;

  /**
   * The '<em><b>Serial FCTL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial FCTL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_FCTL
   * @model name="serialFCTL"
   * @generated
   * @ordered
   */
  public static final int SERIAL_FCTL_VALUE = 39;

  /**
   * The '<em><b>Menu Simm</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Simm</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_SIMM
   * @model name="menuSimm"
   * @generated
   * @ordered
   */
  public static final int MENU_SIMM_VALUE = 40;

  /**
   * The '<em><b>Compress ALG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Compress ALG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COMPRESS_ALG
   * @model name="compressALG"
   * @generated
   * @ordered
   */
  public static final int COMPRESS_ALG_VALUE = 41;

  /**
   * The '<em><b>ASub EFLG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ASub EFLG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASUB_EFLG
   * @model name="aSubEFLG"
   * @generated
   * @ordered
   */
  public static final int ASUB_EFLG_VALUE = 42;

  /**
   * The '<em><b>Fanout SELM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Fanout SELM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FANOUT_SELM
   * @model name="fanoutSELM"
   * @generated
   * @ordered
   */
  public static final int FANOUT_SELM_VALUE = 43;

  /**
   * The '<em><b>Calcout OOPT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Calcout OOPT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CALCOUT_OOPT
   * @model name="calcoutOOPT"
   * @generated
   * @ordered
   */
  public static final int CALCOUT_OOPT_VALUE = 44;

  /**
   * The '<em><b>Asyn ENABLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Asyn ENABLE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASYN_ENABLE
   * @model name="asynENABLE"
   * @generated
   * @ordered
   */
  public static final int ASYN_ENABLE_VALUE = 45;

  /**
   * The '<em><b>Epid Feedback Mode</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Epid Feedback Mode</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EPID_FEEDBACK_MODE
   * @model name="epidFeedbackMode"
   * @generated
   * @ordered
   */
  public static final int EPID_FEEDBACK_MODE_VALUE = 46;

  /**
   * The '<em><b>Menu Convert</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Convert</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_CONVERT
   * @model name="menuConvert"
   * @generated
   * @ordered
   */
  public static final int MENU_CONVERT_VALUE = 47;

  /**
   * The '<em><b>Scaler CNT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Scaler CNT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCALER_CNT
   * @model name="scalerCNT"
   * @generated
   * @ordered
   */
  public static final int SCALER_CNT_VALUE = 48;

  /**
   * The '<em><b>Serial IX</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial IX</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_IX
   * @model name="serialIX"
   * @generated
   * @ordered
   */
  public static final int SERIAL_IX_VALUE = 49;

  /**
   * The '<em><b>Menu Yes No</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Menu Yes No</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MENU_YES_NO
   * @model name="menuYesNo"
   * @generated
   * @ordered
   */
  public static final int MENU_YES_NO_VALUE = 50;

  /**
   * The '<em><b>Timestamp TST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Timestamp TST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TIMESTAMP_TST
   * @model name="timestampTST"
   * @generated
   * @ordered
   */
  public static final int TIMESTAMP_TST_VALUE = 51;

  /**
   * The '<em><b>Serial DBIT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Serial DBIT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SERIAL_DBIT
   * @model name="serialDBIT"
   * @generated
   * @ordered
   */
  public static final int SERIAL_DBIT_VALUE = 52;

  /**
   * The '<em><b>Sel SELM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Sel SELM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SEL_SELM
   * @model name="selSELM"
   * @generated
   * @ordered
   */
  public static final int SEL_SELM_VALUE = 53;

  /**
   * An array of all the '<em><b>Menunames</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Menunames[] VALUES_ARRAY =
    new Menunames[]
    {
      SERIAL_PRTY,
      WAVEFORM_POST,
      AAO_POST,
      MENU_PRIORITY,
      SERIAL_SBIT,
      CALCOUT_DOPT,
      SDIS,
      MENU_OMSL,
      MENU_FTYPE,
      STRINGIN_POST,
      MENU_PINI,
      DFANOUT_SELM,
      MENU_SCAN,
      GPIB_ACMD,
      ASUB_LFLG,
      ASYN_TMOD,
      SCALER_D1,
      MENU_POST,
      ASYN_INTERFACE,
      MENU_ALARM_STAT,
      AO_OIF,
      BUFFERING_ALG,
      AAI_POST,
      EPID_FEEDBACK_STATE,
      CALCOUT_INAV,
      ASYN_AUTOCONNECT,
      ASYN_FMT,
      ASYN_CONNECT,
      GPIB_UCMD,
      SERIAL_BAUD,
      HISTOGRAM_CMD,
      ASYN_TRACE,
      SCALER_G1,
      ASYN_EOMREASON,
      SCALER_CONT,
      MENU_IVOA,
      STRINGOUT_POST,
      MENU_ALARM_SEVR,
      SERIAL_MCTL,
      SERIAL_FCTL,
      MENU_SIMM,
      COMPRESS_ALG,
      ASUB_EFLG,
      FANOUT_SELM,
      CALCOUT_OOPT,
      ASYN_ENABLE,
      EPID_FEEDBACK_MODE,
      MENU_CONVERT,
      SCALER_CNT,
      SERIAL_IX,
      MENU_YES_NO,
      TIMESTAMP_TST,
      SERIAL_DBIT,
      SEL_SELM,
    };

  /**
   * A public read-only list of all the '<em><b>Menunames</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Menunames> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Menunames</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Menunames get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Menunames result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Menunames</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Menunames getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Menunames result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Menunames</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Menunames get(int value)
  {
    switch (value)
    {
      case SERIAL_PRTY_VALUE: return SERIAL_PRTY;
      case WAVEFORM_POST_VALUE: return WAVEFORM_POST;
      case AAO_POST_VALUE: return AAO_POST;
      case MENU_PRIORITY_VALUE: return MENU_PRIORITY;
      case SERIAL_SBIT_VALUE: return SERIAL_SBIT;
      case CALCOUT_DOPT_VALUE: return CALCOUT_DOPT;
      case SDIS_VALUE: return SDIS;
      case MENU_OMSL_VALUE: return MENU_OMSL;
      case MENU_FTYPE_VALUE: return MENU_FTYPE;
      case STRINGIN_POST_VALUE: return STRINGIN_POST;
      case MENU_PINI_VALUE: return MENU_PINI;
      case DFANOUT_SELM_VALUE: return DFANOUT_SELM;
      case MENU_SCAN_VALUE: return MENU_SCAN;
      case GPIB_ACMD_VALUE: return GPIB_ACMD;
      case ASUB_LFLG_VALUE: return ASUB_LFLG;
      case ASYN_TMOD_VALUE: return ASYN_TMOD;
      case SCALER_D1_VALUE: return SCALER_D1;
      case MENU_POST_VALUE: return MENU_POST;
      case ASYN_INTERFACE_VALUE: return ASYN_INTERFACE;
      case MENU_ALARM_STAT_VALUE: return MENU_ALARM_STAT;
      case AO_OIF_VALUE: return AO_OIF;
      case BUFFERING_ALG_VALUE: return BUFFERING_ALG;
      case AAI_POST_VALUE: return AAI_POST;
      case EPID_FEEDBACK_STATE_VALUE: return EPID_FEEDBACK_STATE;
      case CALCOUT_INAV_VALUE: return CALCOUT_INAV;
      case ASYN_AUTOCONNECT_VALUE: return ASYN_AUTOCONNECT;
      case ASYN_FMT_VALUE: return ASYN_FMT;
      case ASYN_CONNECT_VALUE: return ASYN_CONNECT;
      case GPIB_UCMD_VALUE: return GPIB_UCMD;
      case SERIAL_BAUD_VALUE: return SERIAL_BAUD;
      case HISTOGRAM_CMD_VALUE: return HISTOGRAM_CMD;
      case ASYN_TRACE_VALUE: return ASYN_TRACE;
      case SCALER_G1_VALUE: return SCALER_G1;
      case ASYN_EOMREASON_VALUE: return ASYN_EOMREASON;
      case SCALER_CONT_VALUE: return SCALER_CONT;
      case MENU_IVOA_VALUE: return MENU_IVOA;
      case STRINGOUT_POST_VALUE: return STRINGOUT_POST;
      case MENU_ALARM_SEVR_VALUE: return MENU_ALARM_SEVR;
      case SERIAL_MCTL_VALUE: return SERIAL_MCTL;
      case SERIAL_FCTL_VALUE: return SERIAL_FCTL;
      case MENU_SIMM_VALUE: return MENU_SIMM;
      case COMPRESS_ALG_VALUE: return COMPRESS_ALG;
      case ASUB_EFLG_VALUE: return ASUB_EFLG;
      case FANOUT_SELM_VALUE: return FANOUT_SELM;
      case CALCOUT_OOPT_VALUE: return CALCOUT_OOPT;
      case ASYN_ENABLE_VALUE: return ASYN_ENABLE;
      case EPID_FEEDBACK_MODE_VALUE: return EPID_FEEDBACK_MODE;
      case MENU_CONVERT_VALUE: return MENU_CONVERT;
      case SCALER_CNT_VALUE: return SCALER_CNT;
      case SERIAL_IX_VALUE: return SERIAL_IX;
      case MENU_YES_NO_VALUE: return MENU_YES_NO;
      case TIMESTAMP_TST_VALUE: return TIMESTAMP_TST;
      case SERIAL_DBIT_VALUE: return SERIAL_DBIT;
      case SEL_SELM_VALUE: return SEL_SELM;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Menunames(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Menunames
