/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getName <em>Name</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getMenuname <em>Menuname</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getChoices <em>Choices</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getMenu()
 * @model
 * @generated
 */
public interface Menu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getMenu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Menuname</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menuname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menuname</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames
   * @see #setMenuname(Menunames)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getMenu_Menuname()
   * @model
   * @generated
   */
  Menunames getMenuname();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menu#getMenuname <em>Menuname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menuname</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Menunames
   * @see #getMenuname()
   * @generated
   */
  void setMenuname(Menunames value);

  /**
   * Returns the value of the '<em><b>Choices</b></em>' containment reference list.
   * The list contents are of type {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Choice}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Choices</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choices</em>' containment reference list.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getMenu_Choices()
   * @model containment="true"
   * @generated
   */
  EList<Choice> getChoices();

} // Menu
