/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.dbdTextEditor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recordtype</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getName <em>Name</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getRecordtypename <em>Recordtypename</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getRecordtype()
 * @model
 * @generated
 */
public interface Recordtype extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getRecordtype_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Recordtypename</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recordtypename</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recordtypename</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames
   * @see #setRecordtypename(Recordtypenames)
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getRecordtype_Recordtypename()
   * @model
   * @generated
   */
  Recordtypenames getRecordtypename();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtype#getRecordtypename <em>Recordtypename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recordtypename</em>' attribute.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Recordtypenames
   * @see #getRecordtypename()
   * @generated
   */
  void setRecordtypename(Recordtypenames value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.csstudio.xtext.dbdtexteditor.dbdTextEditor.Field}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage#getRecordtype_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // Recordtype
