/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DbdTextEditorRuntimeModule extends AbstractDbdTextEditorRuntimeModule {
}
