/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor;

import org.csstudio.xtext.dbtexteditor.AbstractDbTextEditorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DbTextEditorRuntimeModule extends AbstractDbTextEditorRuntimeModule {
}
