/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.validation;

import org.csstudio.xtext.dbdtexteditor.validation.AbstractDbdTextEditorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DbdTextEditorValidator extends AbstractDbdTextEditorValidator {
}
