/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ui;

import com.google.inject.Injector;
import org.csstudio.xtext.dbdtexteditor.ui.internal.DbdtexteditorActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DbdTextEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DbdtexteditorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DbdtexteditorActivator activator = DbdtexteditorActivator.getInstance();
		return activator != null ? activator.getInjector(DbdtexteditorActivator.ORG_CSSTUDIO_XTEXT_DBDTEXTEDITOR_DBDTEXTEDITOR) : null;
	}

}
