/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.ide;

import org.csstudio.xtext.dbtexteditor.ide.AbstractDbTextEditorIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DbTextEditorIdeModule extends AbstractDbTextEditorIdeModule {
}
