/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.csstudio.xtext.dbtexteditor.DbTextEditorRuntimeModule;
import org.csstudio.xtext.dbtexteditor.DbTextEditorStandaloneSetup;
import org.csstudio.xtext.dbtexteditor.ide.DbTextEditorIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DbTextEditorIdeSetup extends DbTextEditorStandaloneSetup {
  @Override
  public Injector createInjector() {
    DbTextEditorRuntimeModule _dbTextEditorRuntimeModule = new DbTextEditorRuntimeModule();
    DbTextEditorIdeModule _dbTextEditorIdeModule = new DbTextEditorIdeModule();
    return Guice.createInjector(Modules2.mixin(_dbTextEditorRuntimeModule, _dbTextEditorIdeModule));
  }
}
