/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.ide


/**
 * Use this class to register ide components.
 */
class DbTextEditorIdeModule extends AbstractDbTextEditorIdeModule {
}
