/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor;

import org.csstudio.xtext.dbdtexteditor.AbstractDbdTextEditorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DbdTextEditorRuntimeModule extends AbstractDbdTextEditorRuntimeModule {
}
