/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.ui.contentassist;

import org.csstudio.xtext.dbtexteditor.ui.contentassist.AbstractDbTextEditorProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DbTextEditorProposalProvider extends AbstractDbTextEditorProposalProvider {
}
