/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DbTextEditorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DbModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.dbModel");
		private final Assignment cRecordsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRecordsRecordParserRuleCall_0 = (RuleCall)cRecordsAssignment.eContents().get(0);
		
		//dbModel:
		//	records+=Record*;
		@Override public ParserRule getRule() { return rule; }
		
		//records+=Record*
		public Assignment getRecordsAssignment() { return cRecordsAssignment; }
		
		//Record
		public RuleCall getRecordsRecordParserRuleCall_0() { return cRecordsRecordParserRuleCall_0; }
	}
	public class RecordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.Record");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameRecordKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRecordnameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRecordnameRecordnamesEnumRuleCall_2_0 = (RuleCall)cRecordnameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRecordLinkAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRecordLinkSTRINGTerminalRuleCall_4_0 = (RuleCall)cRecordLinkAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInfosfieldsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final Alternatives cInfosfieldsAlternatives_7_0 = (Alternatives)cInfosfieldsAssignment_7.eContents().get(0);
		private final RuleCall cInfosfieldsInfoParserRuleCall_7_0_0 = (RuleCall)cInfosfieldsAlternatives_7_0.eContents().get(0);
		private final RuleCall cInfosfieldsFieldParserRuleCall_7_0_1 = (RuleCall)cInfosfieldsAlternatives_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Record:
		//	name='record' '(' recordname=Recordnames ',' recordLink=STRING ')' '{'
		//	infosfields+=(Info | Field)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name='record' '(' recordname=Recordnames ',' recordLink=STRING ')' '{' infosfields+=(Info | Field)* '}'
		public Group getGroup() { return cGroup; }
		
		//name='record'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'record'
		public Keyword getNameRecordKeyword_0_0() { return cNameRecordKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//recordname=Recordnames
		public Assignment getRecordnameAssignment_2() { return cRecordnameAssignment_2; }
		
		//Recordnames
		public RuleCall getRecordnameRecordnamesEnumRuleCall_2_0() { return cRecordnameRecordnamesEnumRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//recordLink=STRING
		public Assignment getRecordLinkAssignment_4() { return cRecordLinkAssignment_4; }
		
		//STRING
		public RuleCall getRecordLinkSTRINGTerminalRuleCall_4_0() { return cRecordLinkSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//infosfields+=(Info | Field)*
		public Assignment getInfosfieldsAssignment_7() { return cInfosfieldsAssignment_7; }
		
		//(Info | Field)
		public Alternatives getInfosfieldsAlternatives_7_0() { return cInfosfieldsAlternatives_7_0; }
		
		//Info
		public RuleCall getInfosfieldsInfoParserRuleCall_7_0_0() { return cInfosfieldsInfoParserRuleCall_7_0_0; }
		
		//Field
		public RuleCall getInfosfieldsFieldParserRuleCall_7_0_1() { return cInfosfieldsFieldParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameFieldKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFieldnameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFieldnameFieldnamesEnumRuleCall_2_0 = (RuleCall)cFieldnameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cFieldstringAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cFieldstringSTRINGTerminalRuleCall_4_0_0 = (RuleCall)cFieldstringAssignment_4_0.eContents().get(0);
		private final Assignment cFieldintAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cFieldintINTTerminalRuleCall_4_1_0 = (RuleCall)cFieldintAssignment_4_1.eContents().get(0);
		private final Assignment cFielddoubleAssignment_4_2 = (Assignment)cAlternatives_4.eContents().get(2);
		private final RuleCall cFielddoubleDOUBLEParserRuleCall_4_2_0 = (RuleCall)cFielddoubleAssignment_4_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Field:
		//	name='field' '(' fieldname=Fieldnames ',' (fieldstring=STRING | fieldint=INT | fielddouble=DOUBLE) ')';
		@Override public ParserRule getRule() { return rule; }
		
		//name='field' '(' fieldname=Fieldnames ',' (fieldstring=STRING | fieldint=INT | fielddouble=DOUBLE) ')'
		public Group getGroup() { return cGroup; }
		
		//name='field'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'field'
		public Keyword getNameFieldKeyword_0_0() { return cNameFieldKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//fieldname=Fieldnames
		public Assignment getFieldnameAssignment_2() { return cFieldnameAssignment_2; }
		
		//Fieldnames
		public RuleCall getFieldnameFieldnamesEnumRuleCall_2_0() { return cFieldnameFieldnamesEnumRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//fieldstring=STRING | fieldint=INT | fielddouble=DOUBLE
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//fieldstring=STRING
		public Assignment getFieldstringAssignment_4_0() { return cFieldstringAssignment_4_0; }
		
		//STRING
		public RuleCall getFieldstringSTRINGTerminalRuleCall_4_0_0() { return cFieldstringSTRINGTerminalRuleCall_4_0_0; }
		
		//fieldint=INT
		public Assignment getFieldintAssignment_4_1() { return cFieldintAssignment_4_1; }
		
		//INT
		public RuleCall getFieldintINTTerminalRuleCall_4_1_0() { return cFieldintINTTerminalRuleCall_4_1_0; }
		
		//fielddouble=DOUBLE
		public Assignment getFielddoubleAssignment_4_2() { return cFielddoubleAssignment_4_2; }
		
		//DOUBLE
		public RuleCall getFielddoubleDOUBLEParserRuleCall_4_2_0() { return cFielddoubleDOUBLEParserRuleCall_4_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class InfoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.Info");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInfoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cNameAsynREADBACKKeyword_2_0 = (Keyword)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInfoValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInfoValueSTRINGTerminalRuleCall_4_0 = (RuleCall)cInfoValueAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Info:
		//	'info' '(' name='asyn:READBACK' ',' infoValue=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'info' '(' name='asyn:READBACK' ',' infoValue=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'info'
		public Keyword getInfoKeyword_0() { return cInfoKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//name='asyn:READBACK'
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//'asyn:READBACK'
		public Keyword getNameAsynREADBACKKeyword_2_0() { return cNameAsynREADBACKKeyword_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//infoValue=STRING
		public Assignment getInfoValueAssignment_4() { return cInfoValueAssignment_4; }
		
		//STRING
		public RuleCall getInfoValueSTRINGTerminalRuleCall_4_0() { return cInfoValueSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class DOUBLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.DOUBLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//DOUBLE:
		//	INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	
	public class FieldnamesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.Fieldnames");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNAMEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNAMENAMEKeyword_0_0 = (Keyword)cNAMEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDESCEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDESCDESCKeyword_1_0 = (Keyword)cDESCEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cASGEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cASGASGKeyword_2_0 = (Keyword)cASGEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSCANEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSCANSCANKeyword_3_0 = (Keyword)cSCANEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cPHASEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cPHASPHASKeyword_4_0 = (Keyword)cPHASEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPINIEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPINIPINIKeyword_5_0 = (Keyword)cPINIEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSDISEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSDISSDISKeyword_6_0 = (Keyword)cSDISEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cPROCEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cPROCPROCKeyword_7_0 = (Keyword)cPROCEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cPACTEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cPACTPACTKeyword_8_0 = (Keyword)cPACTEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cSEVREnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cSEVRSEVRKeyword_9_0 = (Keyword)cSEVREnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cSTATEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cSTATSTATKeyword_10_0 = (Keyword)cSTATEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cTIMEEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cTIMETIMEKeyword_11_0 = (Keyword)cTIMEEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cDTYPEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cDTYPDTYPKeyword_12_0 = (Keyword)cDTYPEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cONAMEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cONAMONAMKeyword_13_0 = (Keyword)cONAMEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cOSVEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cOSVOSVKeyword_14_0 = (Keyword)cOSVEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cOUTEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cOUTOUTKeyword_15_0 = (Keyword)cOUTEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cSIMLEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cSIMLSIMLKeyword_16_0 = (Keyword)cSIMLEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cZNAMEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cZNAMZNAMKeyword_17_0 = (Keyword)cZNAMEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cZSVEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cZSVZSVKeyword_18_0 = (Keyword)cZSVEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cINPEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cINPINPKeyword_19_0 = (Keyword)cINPEnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cEGUEnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cEGUEGUKeyword_20_0 = (Keyword)cEGUEnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cLINREnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cLINRLINRKeyword_21_0 = (Keyword)cLINREnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cEGULEnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cEGULEGULKeyword_22_0 = (Keyword)cEGULEnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cEGUFEnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cEGUFEGUFKeyword_23_0 = (Keyword)cEGUFEnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cHIGHEnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cHIGHHIGHKeyword_24_0 = (Keyword)cHIGHEnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cHSVEnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cHSVHSVKeyword_25_0 = (Keyword)cHSVEnumLiteralDeclaration_25.eContents().get(0);
		private final EnumLiteralDeclaration cHIHIEnumLiteralDeclaration_26 = (EnumLiteralDeclaration)cAlternatives.eContents().get(26);
		private final Keyword cHIHIHIHIKeyword_26_0 = (Keyword)cHIHIEnumLiteralDeclaration_26.eContents().get(0);
		private final EnumLiteralDeclaration cHHSVEnumLiteralDeclaration_27 = (EnumLiteralDeclaration)cAlternatives.eContents().get(27);
		private final Keyword cHHSVHHSVKeyword_27_0 = (Keyword)cHHSVEnumLiteralDeclaration_27.eContents().get(0);
		private final EnumLiteralDeclaration cEISTEnumLiteralDeclaration_28 = (EnumLiteralDeclaration)cAlternatives.eContents().get(28);
		private final Keyword cEISTEISTKeyword_28_0 = (Keyword)cEISTEnumLiteralDeclaration_28.eContents().get(0);
		private final EnumLiteralDeclaration cEISVEnumLiteralDeclaration_29 = (EnumLiteralDeclaration)cAlternatives.eContents().get(29);
		private final Keyword cEISVEISVKeyword_29_0 = (Keyword)cEISVEnumLiteralDeclaration_29.eContents().get(0);
		private final EnumLiteralDeclaration cEIVLEnumLiteralDeclaration_30 = (EnumLiteralDeclaration)cAlternatives.eContents().get(30);
		private final Keyword cEIVLEIVLKeyword_30_0 = (Keyword)cEIVLEnumLiteralDeclaration_30.eContents().get(0);
		private final EnumLiteralDeclaration cELSTEnumLiteralDeclaration_31 = (EnumLiteralDeclaration)cAlternatives.eContents().get(31);
		private final Keyword cELSTELSTKeyword_31_0 = (Keyword)cELSTEnumLiteralDeclaration_31.eContents().get(0);
		private final EnumLiteralDeclaration cELSVEnumLiteralDeclaration_32 = (EnumLiteralDeclaration)cAlternatives.eContents().get(32);
		private final Keyword cELSVELSVKeyword_32_0 = (Keyword)cELSVEnumLiteralDeclaration_32.eContents().get(0);
		private final EnumLiteralDeclaration cELVLEnumLiteralDeclaration_33 = (EnumLiteralDeclaration)cAlternatives.eContents().get(33);
		private final Keyword cELVLELVLKeyword_33_0 = (Keyword)cELVLEnumLiteralDeclaration_33.eContents().get(0);
		private final EnumLiteralDeclaration cFRSTEnumLiteralDeclaration_34 = (EnumLiteralDeclaration)cAlternatives.eContents().get(34);
		private final Keyword cFRSTFRSTKeyword_34_0 = (Keyword)cFRSTEnumLiteralDeclaration_34.eContents().get(0);
		private final EnumLiteralDeclaration cFRSVEnumLiteralDeclaration_35 = (EnumLiteralDeclaration)cAlternatives.eContents().get(35);
		private final Keyword cFRSVFRSVKeyword_35_0 = (Keyword)cFRSVEnumLiteralDeclaration_35.eContents().get(0);
		private final EnumLiteralDeclaration cFRVLEnumLiteralDeclaration_36 = (EnumLiteralDeclaration)cAlternatives.eContents().get(36);
		private final Keyword cFRVLFRVLKeyword_36_0 = (Keyword)cFRVLEnumLiteralDeclaration_36.eContents().get(0);
		private final EnumLiteralDeclaration cFVSTEnumLiteralDeclaration_37 = (EnumLiteralDeclaration)cAlternatives.eContents().get(37);
		private final Keyword cFVSTFVSTKeyword_37_0 = (Keyword)cFVSTEnumLiteralDeclaration_37.eContents().get(0);
		private final EnumLiteralDeclaration cHYSTEnumLiteralDeclaration_38 = (EnumLiteralDeclaration)cAlternatives.eContents().get(38);
		private final Keyword cHYSTHYSTKeyword_38_0 = (Keyword)cHYSTEnumLiteralDeclaration_38.eContents().get(0);
		private final EnumLiteralDeclaration cLLSVEnumLiteralDeclaration_39 = (EnumLiteralDeclaration)cAlternatives.eContents().get(39);
		private final Keyword cLLSVLLSVKeyword_39_0 = (Keyword)cLLSVEnumLiteralDeclaration_39.eContents().get(0);
		private final EnumLiteralDeclaration cFVSVEnumLiteralDeclaration_40 = (EnumLiteralDeclaration)cAlternatives.eContents().get(40);
		private final Keyword cFVSVFVSVKeyword_40_0 = (Keyword)cFVSVEnumLiteralDeclaration_40.eContents().get(0);
		private final EnumLiteralDeclaration cFVVLEnumLiteralDeclaration_41 = (EnumLiteralDeclaration)cAlternatives.eContents().get(41);
		private final Keyword cFVVLFVVLKeyword_41_0 = (Keyword)cFVVLEnumLiteralDeclaration_41.eContents().get(0);
		private final EnumLiteralDeclaration cMASKEnumLiteralDeclaration_42 = (EnumLiteralDeclaration)cAlternatives.eContents().get(42);
		private final Keyword cMASKMASKKeyword_42_0 = (Keyword)cMASKEnumLiteralDeclaration_42.eContents().get(0);
		private final EnumLiteralDeclaration cNISTEnumLiteralDeclaration_43 = (EnumLiteralDeclaration)cAlternatives.eContents().get(43);
		private final Keyword cNISTNISTKeyword_43_0 = (Keyword)cNISTEnumLiteralDeclaration_43.eContents().get(0);
		private final EnumLiteralDeclaration cNISVEnumLiteralDeclaration_44 = (EnumLiteralDeclaration)cAlternatives.eContents().get(44);
		private final Keyword cNISVNISVKeyword_44_0 = (Keyword)cNISVEnumLiteralDeclaration_44.eContents().get(0);
		private final EnumLiteralDeclaration cNIVLEnumLiteralDeclaration_45 = (EnumLiteralDeclaration)cAlternatives.eContents().get(45);
		private final Keyword cNIVLNIVLKeyword_45_0 = (Keyword)cNIVLEnumLiteralDeclaration_45.eContents().get(0);
		private final EnumLiteralDeclaration cNOBTEnumLiteralDeclaration_46 = (EnumLiteralDeclaration)cAlternatives.eContents().get(46);
		private final Keyword cNOBTNOBTKeyword_46_0 = (Keyword)cNOBTEnumLiteralDeclaration_46.eContents().get(0);
		private final EnumLiteralDeclaration cONSTEnumLiteralDeclaration_47 = (EnumLiteralDeclaration)cAlternatives.eContents().get(47);
		private final Keyword cONSTONSTKeyword_47_0 = (Keyword)cONSTEnumLiteralDeclaration_47.eContents().get(0);
		private final EnumLiteralDeclaration cONSVEnumLiteralDeclaration_48 = (EnumLiteralDeclaration)cAlternatives.eContents().get(48);
		private final Keyword cONSVONSVKeyword_48_0 = (Keyword)cONSVEnumLiteralDeclaration_48.eContents().get(0);
		private final EnumLiteralDeclaration cONVLEnumLiteralDeclaration_49 = (EnumLiteralDeclaration)cAlternatives.eContents().get(49);
		private final Keyword cONVLONVLKeyword_49_0 = (Keyword)cONVLEnumLiteralDeclaration_49.eContents().get(0);
		private final EnumLiteralDeclaration cSHFTEnumLiteralDeclaration_50 = (EnumLiteralDeclaration)cAlternatives.eContents().get(50);
		private final Keyword cSHFTSHFTKeyword_50_0 = (Keyword)cSHFTEnumLiteralDeclaration_50.eContents().get(0);
		private final EnumLiteralDeclaration cSVSTEnumLiteralDeclaration_51 = (EnumLiteralDeclaration)cAlternatives.eContents().get(51);
		private final Keyword cSVSTSVSTKeyword_51_0 = (Keyword)cSVSTEnumLiteralDeclaration_51.eContents().get(0);
		private final EnumLiteralDeclaration cSVSVEnumLiteralDeclaration_52 = (EnumLiteralDeclaration)cAlternatives.eContents().get(52);
		private final Keyword cSVSVSVSVKeyword_52_0 = (Keyword)cSVSVEnumLiteralDeclaration_52.eContents().get(0);
		private final EnumLiteralDeclaration cSVVLEnumLiteralDeclaration_53 = (EnumLiteralDeclaration)cAlternatives.eContents().get(53);
		private final Keyword cSVVLSVVLKeyword_53_0 = (Keyword)cSVVLEnumLiteralDeclaration_53.eContents().get(0);
		private final EnumLiteralDeclaration cSXSTEnumLiteralDeclaration_54 = (EnumLiteralDeclaration)cAlternatives.eContents().get(54);
		private final Keyword cSXSTSXSTKeyword_54_0 = (Keyword)cSXSTEnumLiteralDeclaration_54.eContents().get(0);
		private final EnumLiteralDeclaration cSXSVEnumLiteralDeclaration_55 = (EnumLiteralDeclaration)cAlternatives.eContents().get(55);
		private final Keyword cSXSVSXSVKeyword_55_0 = (Keyword)cSXSVEnumLiteralDeclaration_55.eContents().get(0);
		private final EnumLiteralDeclaration cSXVLEnumLiteralDeclaration_56 = (EnumLiteralDeclaration)cAlternatives.eContents().get(56);
		private final Keyword cSXVLSXVLKeyword_56_0 = (Keyword)cSXVLEnumLiteralDeclaration_56.eContents().get(0);
		private final EnumLiteralDeclaration cTESTEnumLiteralDeclaration_57 = (EnumLiteralDeclaration)cAlternatives.eContents().get(57);
		private final Keyword cTESTTESTKeyword_57_0 = (Keyword)cTESTEnumLiteralDeclaration_57.eContents().get(0);
		private final EnumLiteralDeclaration cTESVEnumLiteralDeclaration_58 = (EnumLiteralDeclaration)cAlternatives.eContents().get(58);
		private final Keyword cTESVTESVKeyword_58_0 = (Keyword)cTESVEnumLiteralDeclaration_58.eContents().get(0);
		private final EnumLiteralDeclaration cTEVLEnumLiteralDeclaration_59 = (EnumLiteralDeclaration)cAlternatives.eContents().get(59);
		private final Keyword cTEVLTEVLKeyword_59_0 = (Keyword)cTEVLEnumLiteralDeclaration_59.eContents().get(0);
		private final EnumLiteralDeclaration cTHSTEnumLiteralDeclaration_60 = (EnumLiteralDeclaration)cAlternatives.eContents().get(60);
		private final Keyword cTHSTTHSTKeyword_60_0 = (Keyword)cTHSTEnumLiteralDeclaration_60.eContents().get(0);
		private final EnumLiteralDeclaration cTHSVEnumLiteralDeclaration_61 = (EnumLiteralDeclaration)cAlternatives.eContents().get(61);
		private final Keyword cTHSVTHSVKeyword_61_0 = (Keyword)cTHSVEnumLiteralDeclaration_61.eContents().get(0);
		private final EnumLiteralDeclaration cTHVLEnumLiteralDeclaration_62 = (EnumLiteralDeclaration)cAlternatives.eContents().get(62);
		private final Keyword cTHVLTHVLKeyword_62_0 = (Keyword)cTHVLEnumLiteralDeclaration_62.eContents().get(0);
		private final EnumLiteralDeclaration cTWSTEnumLiteralDeclaration_63 = (EnumLiteralDeclaration)cAlternatives.eContents().get(63);
		private final Keyword cTWSTTWSTKeyword_63_0 = (Keyword)cTWSTEnumLiteralDeclaration_63.eContents().get(0);
		private final EnumLiteralDeclaration cTWSVEnumLiteralDeclaration_64 = (EnumLiteralDeclaration)cAlternatives.eContents().get(64);
		private final Keyword cTWSVTWSVKeyword_64_0 = (Keyword)cTWSVEnumLiteralDeclaration_64.eContents().get(0);
		private final EnumLiteralDeclaration cTWVLEnumLiteralDeclaration_65 = (EnumLiteralDeclaration)cAlternatives.eContents().get(65);
		private final Keyword cTWVLTWVLKeyword_65_0 = (Keyword)cTWVLEnumLiteralDeclaration_65.eContents().get(0);
		private final EnumLiteralDeclaration cUNSVEnumLiteralDeclaration_66 = (EnumLiteralDeclaration)cAlternatives.eContents().get(66);
		private final Keyword cUNSVUNSVKeyword_66_0 = (Keyword)cUNSVEnumLiteralDeclaration_66.eContents().get(0);
		private final EnumLiteralDeclaration cZRSTEnumLiteralDeclaration_67 = (EnumLiteralDeclaration)cAlternatives.eContents().get(67);
		private final Keyword cZRSTZRSTKeyword_67_0 = (Keyword)cZRSTEnumLiteralDeclaration_67.eContents().get(0);
		private final EnumLiteralDeclaration cZRSVEnumLiteralDeclaration_68 = (EnumLiteralDeclaration)cAlternatives.eContents().get(68);
		private final Keyword cZRSVZRSVKeyword_68_0 = (Keyword)cZRSVEnumLiteralDeclaration_68.eContents().get(0);
		private final EnumLiteralDeclaration cZRVLEnumLiteralDeclaration_69 = (EnumLiteralDeclaration)cAlternatives.eContents().get(69);
		private final Keyword cZRVLZRVLKeyword_69_0 = (Keyword)cZRVLEnumLiteralDeclaration_69.eContents().get(0);
		private final EnumLiteralDeclaration cLOLOEnumLiteralDeclaration_70 = (EnumLiteralDeclaration)cAlternatives.eContents().get(70);
		private final Keyword cLOLOLOLOKeyword_70_0 = (Keyword)cLOLOEnumLiteralDeclaration_70.eContents().get(0);
		private final EnumLiteralDeclaration cLOWEnumLiteralDeclaration_71 = (EnumLiteralDeclaration)cAlternatives.eContents().get(71);
		private final Keyword cLOWLOWKeyword_71_0 = (Keyword)cLOWEnumLiteralDeclaration_71.eContents().get(0);
		private final EnumLiteralDeclaration cLSVEnumLiteralDeclaration_72 = (EnumLiteralDeclaration)cAlternatives.eContents().get(72);
		private final Keyword cLSVLSVKeyword_72_0 = (Keyword)cLSVEnumLiteralDeclaration_72.eContents().get(0);
		private final EnumLiteralDeclaration cSSCNEnumLiteralDeclaration_73 = (EnumLiteralDeclaration)cAlternatives.eContents().get(73);
		private final Keyword cSSCNSSCNKeyword_73_0 = (Keyword)cSSCNEnumLiteralDeclaration_73.eContents().get(0);
		private final EnumLiteralDeclaration cTSEEnumLiteralDeclaration_74 = (EnumLiteralDeclaration)cAlternatives.eContents().get(74);
		private final Keyword cTSETSEKeyword_74_0 = (Keyword)cTSEEnumLiteralDeclaration_74.eContents().get(0);
		private final EnumLiteralDeclaration cPRECEnumLiteralDeclaration_75 = (EnumLiteralDeclaration)cAlternatives.eContents().get(75);
		private final Keyword cPRECPRECKeyword_75_0 = (Keyword)cPRECEnumLiteralDeclaration_75.eContents().get(0);
		private final EnumLiteralDeclaration cDRVHEnumLiteralDeclaration_76 = (EnumLiteralDeclaration)cAlternatives.eContents().get(76);
		private final Keyword cDRVHDRVHKeyword_76_0 = (Keyword)cDRVHEnumLiteralDeclaration_76.eContents().get(0);
		private final EnumLiteralDeclaration cLOPREnumLiteralDeclaration_77 = (EnumLiteralDeclaration)cAlternatives.eContents().get(77);
		private final Keyword cLOPRLOPRKeyword_77_0 = (Keyword)cLOPREnumLiteralDeclaration_77.eContents().get(0);
		private final EnumLiteralDeclaration cDRVLEnumLiteralDeclaration_78 = (EnumLiteralDeclaration)cAlternatives.eContents().get(78);
		private final Keyword cDRVLDRVLKeyword_78_0 = (Keyword)cDRVLEnumLiteralDeclaration_78.eContents().get(0);
		private final EnumLiteralDeclaration cHOPREnumLiteralDeclaration_79 = (EnumLiteralDeclaration)cAlternatives.eContents().get(79);
		private final Keyword cHOPRHOPRKeyword_79_0 = (Keyword)cHOPREnumLiteralDeclaration_79.eContents().get(0);
		private final EnumLiteralDeclaration cCALCEnumLiteralDeclaration_80 = (EnumLiteralDeclaration)cAlternatives.eContents().get(80);
		private final Keyword cCALCCALCKeyword_80_0 = (Keyword)cCALCEnumLiteralDeclaration_80.eContents().get(0);
		private final EnumLiteralDeclaration cINPAEnumLiteralDeclaration_81 = (EnumLiteralDeclaration)cAlternatives.eContents().get(81);
		private final Keyword cINPAINPAKeyword_81_0 = (Keyword)cINPAEnumLiteralDeclaration_81.eContents().get(0);
		private final EnumLiteralDeclaration cINPBEnumLiteralDeclaration_82 = (EnumLiteralDeclaration)cAlternatives.eContents().get(82);
		private final Keyword cINPBINPBKeyword_82_0 = (Keyword)cINPBEnumLiteralDeclaration_82.eContents().get(0);
		private final EnumLiteralDeclaration cINPCEnumLiteralDeclaration_83 = (EnumLiteralDeclaration)cAlternatives.eContents().get(83);
		private final Keyword cINPCINPCKeyword_83_0 = (Keyword)cINPCEnumLiteralDeclaration_83.eContents().get(0);
		private final EnumLiteralDeclaration cINPDEnumLiteralDeclaration_84 = (EnumLiteralDeclaration)cAlternatives.eContents().get(84);
		private final Keyword cINPDINPDKeyword_84_0 = (Keyword)cINPDEnumLiteralDeclaration_84.eContents().get(0);
		private final EnumLiteralDeclaration cFLNKEnumLiteralDeclaration_85 = (EnumLiteralDeclaration)cAlternatives.eContents().get(85);
		private final Keyword cFLNKFLNKKeyword_85_0 = (Keyword)cFLNKEnumLiteralDeclaration_85.eContents().get(0);
		private final EnumLiteralDeclaration cINPEEnumLiteralDeclaration_86 = (EnumLiteralDeclaration)cAlternatives.eContents().get(86);
		private final Keyword cINPEINPEKeyword_86_0 = (Keyword)cINPEEnumLiteralDeclaration_86.eContents().get(0);
		private final EnumLiteralDeclaration cINPFEnumLiteralDeclaration_87 = (EnumLiteralDeclaration)cAlternatives.eContents().get(87);
		private final Keyword cINPFINPFKeyword_87_0 = (Keyword)cINPFEnumLiteralDeclaration_87.eContents().get(0);
		private final EnumLiteralDeclaration cINPGEnumLiteralDeclaration_88 = (EnumLiteralDeclaration)cAlternatives.eContents().get(88);
		private final Keyword cINPGINPGKeyword_88_0 = (Keyword)cINPGEnumLiteralDeclaration_88.eContents().get(0);
		private final EnumLiteralDeclaration cINPHEnumLiteralDeclaration_89 = (EnumLiteralDeclaration)cAlternatives.eContents().get(89);
		private final Keyword cINPHINPHKeyword_89_0 = (Keyword)cINPHEnumLiteralDeclaration_89.eContents().get(0);
		private final EnumLiteralDeclaration cINPIEnumLiteralDeclaration_90 = (EnumLiteralDeclaration)cAlternatives.eContents().get(90);
		private final Keyword cINPIINPIKeyword_90_0 = (Keyword)cINPIEnumLiteralDeclaration_90.eContents().get(0);
		private final EnumLiteralDeclaration cINPJEnumLiteralDeclaration_91 = (EnumLiteralDeclaration)cAlternatives.eContents().get(91);
		private final Keyword cINPJINPJKeyword_91_0 = (Keyword)cINPJEnumLiteralDeclaration_91.eContents().get(0);
		private final EnumLiteralDeclaration cINPKEnumLiteralDeclaration_92 = (EnumLiteralDeclaration)cAlternatives.eContents().get(92);
		private final Keyword cINPKINPKKeyword_92_0 = (Keyword)cINPKEnumLiteralDeclaration_92.eContents().get(0);
		private final EnumLiteralDeclaration cINAAEnumLiteralDeclaration_93 = (EnumLiteralDeclaration)cAlternatives.eContents().get(93);
		private final Keyword cINAAINAAKeyword_93_0 = (Keyword)cINAAEnumLiteralDeclaration_93.eContents().get(0);
		private final EnumLiteralDeclaration cINBBEnumLiteralDeclaration_94 = (EnumLiteralDeclaration)cAlternatives.eContents().get(94);
		private final Keyword cINBBINBBKeyword_94_0 = (Keyword)cINBBEnumLiteralDeclaration_94.eContents().get(0);
		private final EnumLiteralDeclaration cINCCEnumLiteralDeclaration_95 = (EnumLiteralDeclaration)cAlternatives.eContents().get(95);
		private final Keyword cINCCINCCKeyword_95_0 = (Keyword)cINCCEnumLiteralDeclaration_95.eContents().get(0);
		private final EnumLiteralDeclaration cSIOLEnumLiteralDeclaration_96 = (EnumLiteralDeclaration)cAlternatives.eContents().get(96);
		private final Keyword cSIOLSIOLKeyword_96_0 = (Keyword)cSIOLEnumLiteralDeclaration_96.eContents().get(0);
		
		//enum Fieldnames:
		//	NAME | DESC | ASG | SCAN | PHAS | PINI | SDIS | PROC |
		//	PACT | SEVR | STAT | TIME | DTYP | ONAM | OSV | OUT |
		//	SIML | ZNAM | ZSV | INP | EGU | LINR | EGUL | EGUF |
		//	HIGH | HSV | HIHI | HHSV | EIST | EISV | EIVL | ELST |
		//	ELSV | ELVL | FRST | FRSV | FRVL | FVST | HYST | LLSV
		//	| FVSV | FVVL | MASK | NIST | NISV | NIVL | NOBT | ONST
		//	| ONSV | ONVL | SHFT | SVST | SVSV | SVVL | SXST |
		//	SXSV | SXVL | TEST | TESV | TEVL | THST | THSV | THVL
		//	| TWST | TWSV | TWVL | UNSV | ZRST | ZRSV | ZRVL
		//	| LOLO | LOW | LSV | SSCN | TSE | PREC | DRVH | LOPR
		//	| DRVL | HOPR | CALC | INPA | INPB | INPC | INPD
		//	| FLNK | INPE | INPF | INPG | INPH | INPI | INPJ
		//	| INPK | INAA | INBB | INCC | SIOL;
		public EnumRule getRule() { return rule; }
		
		//NAME | DESC | ASG | SCAN | PHAS | PINI | SDIS | PROC | PACT | SEVR | STAT | TIME | DTYP | ONAM | OSV | OUT | SIML | ZNAM
		//| ZSV | INP | EGU | LINR | EGUL | EGUF | HIGH | HSV | HIHI | HHSV | EIST | EISV | EIVL | ELST | ELSV | ELVL | FRST |
		//FRSV | FRVL | FVST | HYST | LLSV | FVSV | FVVL | MASK | NIST | NISV | NIVL | NOBT | ONST | ONSV | ONVL | SHFT | SVST |
		//SVSV | SVVL | SXST | SXSV | SXVL | TEST | TESV | TEVL | THST | THSV | THVL | TWST | TWSV | TWVL | UNSV | ZRST | ZRSV |
		//ZRVL | LOLO | LOW | LSV | SSCN | TSE | PREC | DRVH | LOPR | DRVL | HOPR | CALC | INPA | INPB | INPC | INPD | FLNK |
		//INPE | INPF | INPG | INPH | INPI | INPJ | INPK | INAA | INBB | INCC | SIOL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NAME
		public EnumLiteralDeclaration getNAMEEnumLiteralDeclaration_0() { return cNAMEEnumLiteralDeclaration_0; }
		
		//"NAME"
		public Keyword getNAMENAMEKeyword_0_0() { return cNAMENAMEKeyword_0_0; }
		
		//DESC
		public EnumLiteralDeclaration getDESCEnumLiteralDeclaration_1() { return cDESCEnumLiteralDeclaration_1; }
		
		//"DESC"
		public Keyword getDESCDESCKeyword_1_0() { return cDESCDESCKeyword_1_0; }
		
		//ASG
		public EnumLiteralDeclaration getASGEnumLiteralDeclaration_2() { return cASGEnumLiteralDeclaration_2; }
		
		//"ASG"
		public Keyword getASGASGKeyword_2_0() { return cASGASGKeyword_2_0; }
		
		//SCAN
		public EnumLiteralDeclaration getSCANEnumLiteralDeclaration_3() { return cSCANEnumLiteralDeclaration_3; }
		
		//"SCAN"
		public Keyword getSCANSCANKeyword_3_0() { return cSCANSCANKeyword_3_0; }
		
		//PHAS
		public EnumLiteralDeclaration getPHASEnumLiteralDeclaration_4() { return cPHASEnumLiteralDeclaration_4; }
		
		//"PHAS"
		public Keyword getPHASPHASKeyword_4_0() { return cPHASPHASKeyword_4_0; }
		
		//PINI
		public EnumLiteralDeclaration getPINIEnumLiteralDeclaration_5() { return cPINIEnumLiteralDeclaration_5; }
		
		//"PINI"
		public Keyword getPINIPINIKeyword_5_0() { return cPINIPINIKeyword_5_0; }
		
		//SDIS
		public EnumLiteralDeclaration getSDISEnumLiteralDeclaration_6() { return cSDISEnumLiteralDeclaration_6; }
		
		//"SDIS"
		public Keyword getSDISSDISKeyword_6_0() { return cSDISSDISKeyword_6_0; }
		
		//PROC
		public EnumLiteralDeclaration getPROCEnumLiteralDeclaration_7() { return cPROCEnumLiteralDeclaration_7; }
		
		//"PROC"
		public Keyword getPROCPROCKeyword_7_0() { return cPROCPROCKeyword_7_0; }
		
		//PACT
		public EnumLiteralDeclaration getPACTEnumLiteralDeclaration_8() { return cPACTEnumLiteralDeclaration_8; }
		
		//"PACT"
		public Keyword getPACTPACTKeyword_8_0() { return cPACTPACTKeyword_8_0; }
		
		//SEVR
		public EnumLiteralDeclaration getSEVREnumLiteralDeclaration_9() { return cSEVREnumLiteralDeclaration_9; }
		
		//"SEVR"
		public Keyword getSEVRSEVRKeyword_9_0() { return cSEVRSEVRKeyword_9_0; }
		
		//STAT
		public EnumLiteralDeclaration getSTATEnumLiteralDeclaration_10() { return cSTATEnumLiteralDeclaration_10; }
		
		//"STAT"
		public Keyword getSTATSTATKeyword_10_0() { return cSTATSTATKeyword_10_0; }
		
		//TIME
		public EnumLiteralDeclaration getTIMEEnumLiteralDeclaration_11() { return cTIMEEnumLiteralDeclaration_11; }
		
		//"TIME"
		public Keyword getTIMETIMEKeyword_11_0() { return cTIMETIMEKeyword_11_0; }
		
		//DTYP
		public EnumLiteralDeclaration getDTYPEnumLiteralDeclaration_12() { return cDTYPEnumLiteralDeclaration_12; }
		
		//"DTYP"
		public Keyword getDTYPDTYPKeyword_12_0() { return cDTYPDTYPKeyword_12_0; }
		
		//ONAM
		public EnumLiteralDeclaration getONAMEnumLiteralDeclaration_13() { return cONAMEnumLiteralDeclaration_13; }
		
		//"ONAM"
		public Keyword getONAMONAMKeyword_13_0() { return cONAMONAMKeyword_13_0; }
		
		//OSV
		public EnumLiteralDeclaration getOSVEnumLiteralDeclaration_14() { return cOSVEnumLiteralDeclaration_14; }
		
		//"OSV"
		public Keyword getOSVOSVKeyword_14_0() { return cOSVOSVKeyword_14_0; }
		
		//OUT
		public EnumLiteralDeclaration getOUTEnumLiteralDeclaration_15() { return cOUTEnumLiteralDeclaration_15; }
		
		//"OUT"
		public Keyword getOUTOUTKeyword_15_0() { return cOUTOUTKeyword_15_0; }
		
		//SIML
		public EnumLiteralDeclaration getSIMLEnumLiteralDeclaration_16() { return cSIMLEnumLiteralDeclaration_16; }
		
		//"SIML"
		public Keyword getSIMLSIMLKeyword_16_0() { return cSIMLSIMLKeyword_16_0; }
		
		//ZNAM
		public EnumLiteralDeclaration getZNAMEnumLiteralDeclaration_17() { return cZNAMEnumLiteralDeclaration_17; }
		
		//"ZNAM"
		public Keyword getZNAMZNAMKeyword_17_0() { return cZNAMZNAMKeyword_17_0; }
		
		//ZSV
		public EnumLiteralDeclaration getZSVEnumLiteralDeclaration_18() { return cZSVEnumLiteralDeclaration_18; }
		
		//"ZSV"
		public Keyword getZSVZSVKeyword_18_0() { return cZSVZSVKeyword_18_0; }
		
		//INP
		public EnumLiteralDeclaration getINPEnumLiteralDeclaration_19() { return cINPEnumLiteralDeclaration_19; }
		
		//"INP"
		public Keyword getINPINPKeyword_19_0() { return cINPINPKeyword_19_0; }
		
		//EGU
		public EnumLiteralDeclaration getEGUEnumLiteralDeclaration_20() { return cEGUEnumLiteralDeclaration_20; }
		
		//"EGU"
		public Keyword getEGUEGUKeyword_20_0() { return cEGUEGUKeyword_20_0; }
		
		//LINR
		public EnumLiteralDeclaration getLINREnumLiteralDeclaration_21() { return cLINREnumLiteralDeclaration_21; }
		
		//"LINR"
		public Keyword getLINRLINRKeyword_21_0() { return cLINRLINRKeyword_21_0; }
		
		//EGUL
		public EnumLiteralDeclaration getEGULEnumLiteralDeclaration_22() { return cEGULEnumLiteralDeclaration_22; }
		
		//"EGUL"
		public Keyword getEGULEGULKeyword_22_0() { return cEGULEGULKeyword_22_0; }
		
		//EGUF
		public EnumLiteralDeclaration getEGUFEnumLiteralDeclaration_23() { return cEGUFEnumLiteralDeclaration_23; }
		
		//"EGUF"
		public Keyword getEGUFEGUFKeyword_23_0() { return cEGUFEGUFKeyword_23_0; }
		
		//HIGH
		public EnumLiteralDeclaration getHIGHEnumLiteralDeclaration_24() { return cHIGHEnumLiteralDeclaration_24; }
		
		//"HIGH"
		public Keyword getHIGHHIGHKeyword_24_0() { return cHIGHHIGHKeyword_24_0; }
		
		//HSV
		public EnumLiteralDeclaration getHSVEnumLiteralDeclaration_25() { return cHSVEnumLiteralDeclaration_25; }
		
		//"HSV"
		public Keyword getHSVHSVKeyword_25_0() { return cHSVHSVKeyword_25_0; }
		
		//HIHI
		public EnumLiteralDeclaration getHIHIEnumLiteralDeclaration_26() { return cHIHIEnumLiteralDeclaration_26; }
		
		//"HIHI"
		public Keyword getHIHIHIHIKeyword_26_0() { return cHIHIHIHIKeyword_26_0; }
		
		//HHSV
		public EnumLiteralDeclaration getHHSVEnumLiteralDeclaration_27() { return cHHSVEnumLiteralDeclaration_27; }
		
		//"HHSV"
		public Keyword getHHSVHHSVKeyword_27_0() { return cHHSVHHSVKeyword_27_0; }
		
		//EIST
		public EnumLiteralDeclaration getEISTEnumLiteralDeclaration_28() { return cEISTEnumLiteralDeclaration_28; }
		
		//"EIST"
		public Keyword getEISTEISTKeyword_28_0() { return cEISTEISTKeyword_28_0; }
		
		//EISV
		public EnumLiteralDeclaration getEISVEnumLiteralDeclaration_29() { return cEISVEnumLiteralDeclaration_29; }
		
		//"EISV"
		public Keyword getEISVEISVKeyword_29_0() { return cEISVEISVKeyword_29_0; }
		
		//EIVL
		public EnumLiteralDeclaration getEIVLEnumLiteralDeclaration_30() { return cEIVLEnumLiteralDeclaration_30; }
		
		//"EIVL"
		public Keyword getEIVLEIVLKeyword_30_0() { return cEIVLEIVLKeyword_30_0; }
		
		//ELST
		public EnumLiteralDeclaration getELSTEnumLiteralDeclaration_31() { return cELSTEnumLiteralDeclaration_31; }
		
		//"ELST"
		public Keyword getELSTELSTKeyword_31_0() { return cELSTELSTKeyword_31_0; }
		
		//ELSV
		public EnumLiteralDeclaration getELSVEnumLiteralDeclaration_32() { return cELSVEnumLiteralDeclaration_32; }
		
		//"ELSV"
		public Keyword getELSVELSVKeyword_32_0() { return cELSVELSVKeyword_32_0; }
		
		//ELVL
		public EnumLiteralDeclaration getELVLEnumLiteralDeclaration_33() { return cELVLEnumLiteralDeclaration_33; }
		
		//"ELVL"
		public Keyword getELVLELVLKeyword_33_0() { return cELVLELVLKeyword_33_0; }
		
		//FRST
		public EnumLiteralDeclaration getFRSTEnumLiteralDeclaration_34() { return cFRSTEnumLiteralDeclaration_34; }
		
		//"FRST"
		public Keyword getFRSTFRSTKeyword_34_0() { return cFRSTFRSTKeyword_34_0; }
		
		//FRSV
		public EnumLiteralDeclaration getFRSVEnumLiteralDeclaration_35() { return cFRSVEnumLiteralDeclaration_35; }
		
		//"FRSV"
		public Keyword getFRSVFRSVKeyword_35_0() { return cFRSVFRSVKeyword_35_0; }
		
		//FRVL
		public EnumLiteralDeclaration getFRVLEnumLiteralDeclaration_36() { return cFRVLEnumLiteralDeclaration_36; }
		
		//"FRVL"
		public Keyword getFRVLFRVLKeyword_36_0() { return cFRVLFRVLKeyword_36_0; }
		
		//FVST
		public EnumLiteralDeclaration getFVSTEnumLiteralDeclaration_37() { return cFVSTEnumLiteralDeclaration_37; }
		
		//"FVST"
		public Keyword getFVSTFVSTKeyword_37_0() { return cFVSTFVSTKeyword_37_0; }
		
		//HYST
		public EnumLiteralDeclaration getHYSTEnumLiteralDeclaration_38() { return cHYSTEnumLiteralDeclaration_38; }
		
		//"HYST"
		public Keyword getHYSTHYSTKeyword_38_0() { return cHYSTHYSTKeyword_38_0; }
		
		//LLSV
		public EnumLiteralDeclaration getLLSVEnumLiteralDeclaration_39() { return cLLSVEnumLiteralDeclaration_39; }
		
		//"LLSV"
		public Keyword getLLSVLLSVKeyword_39_0() { return cLLSVLLSVKeyword_39_0; }
		
		//FVSV
		public EnumLiteralDeclaration getFVSVEnumLiteralDeclaration_40() { return cFVSVEnumLiteralDeclaration_40; }
		
		//"FVSV"
		public Keyword getFVSVFVSVKeyword_40_0() { return cFVSVFVSVKeyword_40_0; }
		
		//FVVL
		public EnumLiteralDeclaration getFVVLEnumLiteralDeclaration_41() { return cFVVLEnumLiteralDeclaration_41; }
		
		//"FVVL"
		public Keyword getFVVLFVVLKeyword_41_0() { return cFVVLFVVLKeyword_41_0; }
		
		//MASK
		public EnumLiteralDeclaration getMASKEnumLiteralDeclaration_42() { return cMASKEnumLiteralDeclaration_42; }
		
		//"MASK"
		public Keyword getMASKMASKKeyword_42_0() { return cMASKMASKKeyword_42_0; }
		
		//NIST
		public EnumLiteralDeclaration getNISTEnumLiteralDeclaration_43() { return cNISTEnumLiteralDeclaration_43; }
		
		//"NIST"
		public Keyword getNISTNISTKeyword_43_0() { return cNISTNISTKeyword_43_0; }
		
		//NISV
		public EnumLiteralDeclaration getNISVEnumLiteralDeclaration_44() { return cNISVEnumLiteralDeclaration_44; }
		
		//"NISV"
		public Keyword getNISVNISVKeyword_44_0() { return cNISVNISVKeyword_44_0; }
		
		//NIVL
		public EnumLiteralDeclaration getNIVLEnumLiteralDeclaration_45() { return cNIVLEnumLiteralDeclaration_45; }
		
		//"NIVL"
		public Keyword getNIVLNIVLKeyword_45_0() { return cNIVLNIVLKeyword_45_0; }
		
		//NOBT
		public EnumLiteralDeclaration getNOBTEnumLiteralDeclaration_46() { return cNOBTEnumLiteralDeclaration_46; }
		
		//"NOBT"
		public Keyword getNOBTNOBTKeyword_46_0() { return cNOBTNOBTKeyword_46_0; }
		
		//ONST
		public EnumLiteralDeclaration getONSTEnumLiteralDeclaration_47() { return cONSTEnumLiteralDeclaration_47; }
		
		//"ONST"
		public Keyword getONSTONSTKeyword_47_0() { return cONSTONSTKeyword_47_0; }
		
		//ONSV
		public EnumLiteralDeclaration getONSVEnumLiteralDeclaration_48() { return cONSVEnumLiteralDeclaration_48; }
		
		//"ONSV"
		public Keyword getONSVONSVKeyword_48_0() { return cONSVONSVKeyword_48_0; }
		
		//ONVL
		public EnumLiteralDeclaration getONVLEnumLiteralDeclaration_49() { return cONVLEnumLiteralDeclaration_49; }
		
		//"ONVL"
		public Keyword getONVLONVLKeyword_49_0() { return cONVLONVLKeyword_49_0; }
		
		//SHFT
		public EnumLiteralDeclaration getSHFTEnumLiteralDeclaration_50() { return cSHFTEnumLiteralDeclaration_50; }
		
		//"SHFT"
		public Keyword getSHFTSHFTKeyword_50_0() { return cSHFTSHFTKeyword_50_0; }
		
		//SVST
		public EnumLiteralDeclaration getSVSTEnumLiteralDeclaration_51() { return cSVSTEnumLiteralDeclaration_51; }
		
		//"SVST"
		public Keyword getSVSTSVSTKeyword_51_0() { return cSVSTSVSTKeyword_51_0; }
		
		//SVSV
		public EnumLiteralDeclaration getSVSVEnumLiteralDeclaration_52() { return cSVSVEnumLiteralDeclaration_52; }
		
		//"SVSV"
		public Keyword getSVSVSVSVKeyword_52_0() { return cSVSVSVSVKeyword_52_0; }
		
		//SVVL
		public EnumLiteralDeclaration getSVVLEnumLiteralDeclaration_53() { return cSVVLEnumLiteralDeclaration_53; }
		
		//"SVVL"
		public Keyword getSVVLSVVLKeyword_53_0() { return cSVVLSVVLKeyword_53_0; }
		
		//SXST
		public EnumLiteralDeclaration getSXSTEnumLiteralDeclaration_54() { return cSXSTEnumLiteralDeclaration_54; }
		
		//"SXST"
		public Keyword getSXSTSXSTKeyword_54_0() { return cSXSTSXSTKeyword_54_0; }
		
		//SXSV
		public EnumLiteralDeclaration getSXSVEnumLiteralDeclaration_55() { return cSXSVEnumLiteralDeclaration_55; }
		
		//"SXSV"
		public Keyword getSXSVSXSVKeyword_55_0() { return cSXSVSXSVKeyword_55_0; }
		
		//SXVL
		public EnumLiteralDeclaration getSXVLEnumLiteralDeclaration_56() { return cSXVLEnumLiteralDeclaration_56; }
		
		//"SXVL"
		public Keyword getSXVLSXVLKeyword_56_0() { return cSXVLSXVLKeyword_56_0; }
		
		//TEST
		public EnumLiteralDeclaration getTESTEnumLiteralDeclaration_57() { return cTESTEnumLiteralDeclaration_57; }
		
		//"TEST"
		public Keyword getTESTTESTKeyword_57_0() { return cTESTTESTKeyword_57_0; }
		
		//TESV
		public EnumLiteralDeclaration getTESVEnumLiteralDeclaration_58() { return cTESVEnumLiteralDeclaration_58; }
		
		//"TESV"
		public Keyword getTESVTESVKeyword_58_0() { return cTESVTESVKeyword_58_0; }
		
		//TEVL
		public EnumLiteralDeclaration getTEVLEnumLiteralDeclaration_59() { return cTEVLEnumLiteralDeclaration_59; }
		
		//"TEVL"
		public Keyword getTEVLTEVLKeyword_59_0() { return cTEVLTEVLKeyword_59_0; }
		
		//THST
		public EnumLiteralDeclaration getTHSTEnumLiteralDeclaration_60() { return cTHSTEnumLiteralDeclaration_60; }
		
		//"THST"
		public Keyword getTHSTTHSTKeyword_60_0() { return cTHSTTHSTKeyword_60_0; }
		
		//THSV
		public EnumLiteralDeclaration getTHSVEnumLiteralDeclaration_61() { return cTHSVEnumLiteralDeclaration_61; }
		
		//"THSV"
		public Keyword getTHSVTHSVKeyword_61_0() { return cTHSVTHSVKeyword_61_0; }
		
		//THVL
		public EnumLiteralDeclaration getTHVLEnumLiteralDeclaration_62() { return cTHVLEnumLiteralDeclaration_62; }
		
		//"THVL"
		public Keyword getTHVLTHVLKeyword_62_0() { return cTHVLTHVLKeyword_62_0; }
		
		//TWST
		public EnumLiteralDeclaration getTWSTEnumLiteralDeclaration_63() { return cTWSTEnumLiteralDeclaration_63; }
		
		//"TWST"
		public Keyword getTWSTTWSTKeyword_63_0() { return cTWSTTWSTKeyword_63_0; }
		
		//TWSV
		public EnumLiteralDeclaration getTWSVEnumLiteralDeclaration_64() { return cTWSVEnumLiteralDeclaration_64; }
		
		//"TWSV"
		public Keyword getTWSVTWSVKeyword_64_0() { return cTWSVTWSVKeyword_64_0; }
		
		//TWVL
		public EnumLiteralDeclaration getTWVLEnumLiteralDeclaration_65() { return cTWVLEnumLiteralDeclaration_65; }
		
		//"TWVL"
		public Keyword getTWVLTWVLKeyword_65_0() { return cTWVLTWVLKeyword_65_0; }
		
		//UNSV
		public EnumLiteralDeclaration getUNSVEnumLiteralDeclaration_66() { return cUNSVEnumLiteralDeclaration_66; }
		
		//"UNSV"
		public Keyword getUNSVUNSVKeyword_66_0() { return cUNSVUNSVKeyword_66_0; }
		
		//ZRST
		public EnumLiteralDeclaration getZRSTEnumLiteralDeclaration_67() { return cZRSTEnumLiteralDeclaration_67; }
		
		//"ZRST"
		public Keyword getZRSTZRSTKeyword_67_0() { return cZRSTZRSTKeyword_67_0; }
		
		//ZRSV
		public EnumLiteralDeclaration getZRSVEnumLiteralDeclaration_68() { return cZRSVEnumLiteralDeclaration_68; }
		
		//"ZRSV"
		public Keyword getZRSVZRSVKeyword_68_0() { return cZRSVZRSVKeyword_68_0; }
		
		//ZRVL
		public EnumLiteralDeclaration getZRVLEnumLiteralDeclaration_69() { return cZRVLEnumLiteralDeclaration_69; }
		
		//"ZRVL"
		public Keyword getZRVLZRVLKeyword_69_0() { return cZRVLZRVLKeyword_69_0; }
		
		//LOLO
		public EnumLiteralDeclaration getLOLOEnumLiteralDeclaration_70() { return cLOLOEnumLiteralDeclaration_70; }
		
		//"LOLO"
		public Keyword getLOLOLOLOKeyword_70_0() { return cLOLOLOLOKeyword_70_0; }
		
		//LOW
		public EnumLiteralDeclaration getLOWEnumLiteralDeclaration_71() { return cLOWEnumLiteralDeclaration_71; }
		
		//"LOW"
		public Keyword getLOWLOWKeyword_71_0() { return cLOWLOWKeyword_71_0; }
		
		//LSV
		public EnumLiteralDeclaration getLSVEnumLiteralDeclaration_72() { return cLSVEnumLiteralDeclaration_72; }
		
		//"LSV"
		public Keyword getLSVLSVKeyword_72_0() { return cLSVLSVKeyword_72_0; }
		
		//SSCN
		public EnumLiteralDeclaration getSSCNEnumLiteralDeclaration_73() { return cSSCNEnumLiteralDeclaration_73; }
		
		//"SSCN"
		public Keyword getSSCNSSCNKeyword_73_0() { return cSSCNSSCNKeyword_73_0; }
		
		//TSE
		public EnumLiteralDeclaration getTSEEnumLiteralDeclaration_74() { return cTSEEnumLiteralDeclaration_74; }
		
		//"TSE"
		public Keyword getTSETSEKeyword_74_0() { return cTSETSEKeyword_74_0; }
		
		//PREC
		public EnumLiteralDeclaration getPRECEnumLiteralDeclaration_75() { return cPRECEnumLiteralDeclaration_75; }
		
		//"PREC"
		public Keyword getPRECPRECKeyword_75_0() { return cPRECPRECKeyword_75_0; }
		
		//DRVH
		public EnumLiteralDeclaration getDRVHEnumLiteralDeclaration_76() { return cDRVHEnumLiteralDeclaration_76; }
		
		//"DRVH"
		public Keyword getDRVHDRVHKeyword_76_0() { return cDRVHDRVHKeyword_76_0; }
		
		//LOPR
		public EnumLiteralDeclaration getLOPREnumLiteralDeclaration_77() { return cLOPREnumLiteralDeclaration_77; }
		
		//"LOPR"
		public Keyword getLOPRLOPRKeyword_77_0() { return cLOPRLOPRKeyword_77_0; }
		
		//DRVL
		public EnumLiteralDeclaration getDRVLEnumLiteralDeclaration_78() { return cDRVLEnumLiteralDeclaration_78; }
		
		//"DRVL"
		public Keyword getDRVLDRVLKeyword_78_0() { return cDRVLDRVLKeyword_78_0; }
		
		//HOPR
		public EnumLiteralDeclaration getHOPREnumLiteralDeclaration_79() { return cHOPREnumLiteralDeclaration_79; }
		
		//"HOPR"
		public Keyword getHOPRHOPRKeyword_79_0() { return cHOPRHOPRKeyword_79_0; }
		
		//CALC
		public EnumLiteralDeclaration getCALCEnumLiteralDeclaration_80() { return cCALCEnumLiteralDeclaration_80; }
		
		//"CALC"
		public Keyword getCALCCALCKeyword_80_0() { return cCALCCALCKeyword_80_0; }
		
		//INPA
		public EnumLiteralDeclaration getINPAEnumLiteralDeclaration_81() { return cINPAEnumLiteralDeclaration_81; }
		
		//"INPA"
		public Keyword getINPAINPAKeyword_81_0() { return cINPAINPAKeyword_81_0; }
		
		//INPB
		public EnumLiteralDeclaration getINPBEnumLiteralDeclaration_82() { return cINPBEnumLiteralDeclaration_82; }
		
		//"INPB"
		public Keyword getINPBINPBKeyword_82_0() { return cINPBINPBKeyword_82_0; }
		
		//INPC
		public EnumLiteralDeclaration getINPCEnumLiteralDeclaration_83() { return cINPCEnumLiteralDeclaration_83; }
		
		//"INPC"
		public Keyword getINPCINPCKeyword_83_0() { return cINPCINPCKeyword_83_0; }
		
		//INPD
		public EnumLiteralDeclaration getINPDEnumLiteralDeclaration_84() { return cINPDEnumLiteralDeclaration_84; }
		
		//"INPD"
		public Keyword getINPDINPDKeyword_84_0() { return cINPDINPDKeyword_84_0; }
		
		//FLNK
		public EnumLiteralDeclaration getFLNKEnumLiteralDeclaration_85() { return cFLNKEnumLiteralDeclaration_85; }
		
		//"FLNK"
		public Keyword getFLNKFLNKKeyword_85_0() { return cFLNKFLNKKeyword_85_0; }
		
		//INPE
		public EnumLiteralDeclaration getINPEEnumLiteralDeclaration_86() { return cINPEEnumLiteralDeclaration_86; }
		
		//"INPE"
		public Keyword getINPEINPEKeyword_86_0() { return cINPEINPEKeyword_86_0; }
		
		//INPF
		public EnumLiteralDeclaration getINPFEnumLiteralDeclaration_87() { return cINPFEnumLiteralDeclaration_87; }
		
		//"INPF"
		public Keyword getINPFINPFKeyword_87_0() { return cINPFINPFKeyword_87_0; }
		
		//INPG
		public EnumLiteralDeclaration getINPGEnumLiteralDeclaration_88() { return cINPGEnumLiteralDeclaration_88; }
		
		//"INPG"
		public Keyword getINPGINPGKeyword_88_0() { return cINPGINPGKeyword_88_0; }
		
		//INPH
		public EnumLiteralDeclaration getINPHEnumLiteralDeclaration_89() { return cINPHEnumLiteralDeclaration_89; }
		
		//"INPH"
		public Keyword getINPHINPHKeyword_89_0() { return cINPHINPHKeyword_89_0; }
		
		//INPI
		public EnumLiteralDeclaration getINPIEnumLiteralDeclaration_90() { return cINPIEnumLiteralDeclaration_90; }
		
		//"INPI"
		public Keyword getINPIINPIKeyword_90_0() { return cINPIINPIKeyword_90_0; }
		
		//INPJ
		public EnumLiteralDeclaration getINPJEnumLiteralDeclaration_91() { return cINPJEnumLiteralDeclaration_91; }
		
		//"INPJ"
		public Keyword getINPJINPJKeyword_91_0() { return cINPJINPJKeyword_91_0; }
		
		//INPK
		public EnumLiteralDeclaration getINPKEnumLiteralDeclaration_92() { return cINPKEnumLiteralDeclaration_92; }
		
		//"INPK"
		public Keyword getINPKINPKKeyword_92_0() { return cINPKINPKKeyword_92_0; }
		
		//INAA
		public EnumLiteralDeclaration getINAAEnumLiteralDeclaration_93() { return cINAAEnumLiteralDeclaration_93; }
		
		//"INAA"
		public Keyword getINAAINAAKeyword_93_0() { return cINAAINAAKeyword_93_0; }
		
		//INBB
		public EnumLiteralDeclaration getINBBEnumLiteralDeclaration_94() { return cINBBEnumLiteralDeclaration_94; }
		
		//"INBB"
		public Keyword getINBBINBBKeyword_94_0() { return cINBBINBBKeyword_94_0; }
		
		//INCC
		public EnumLiteralDeclaration getINCCEnumLiteralDeclaration_95() { return cINCCEnumLiteralDeclaration_95; }
		
		//"INCC"
		public Keyword getINCCINCCKeyword_95_0() { return cINCCINCCKeyword_95_0; }
		
		//SIOL
		public EnumLiteralDeclaration getSIOLEnumLiteralDeclaration_96() { return cSIOLEnumLiteralDeclaration_96; }
		
		//"SIOL"
		public Keyword getSIOLSIOLKeyword_96_0() { return cSIOLSIOLKeyword_96_0; }
	}
	public class RecordnamesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.Recordnames");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAiEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAiAiKeyword_0_0 = (Keyword)cAiEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAoEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAoAoKeyword_1_0 = (Keyword)cAoEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLonginEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLonginLonginKeyword_2_0 = (Keyword)cLonginEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLongoutEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLongoutLongoutKeyword_3_0 = (Keyword)cLongoutEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cStringinEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cStringinStringinKeyword_4_0 = (Keyword)cStringinEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cStringoutEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cStringoutStringoutKeyword_5_0 = (Keyword)cStringoutEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cLsiEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cLsiLsiKeyword_6_0 = (Keyword)cLsiEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cLsoEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cLsoLsoKeyword_7_0 = (Keyword)cLsoEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cWaveformEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cWaveformWaveformKeyword_8_0 = (Keyword)cWaveformEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cBiEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cBiBiKeyword_9_0 = (Keyword)cBiEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cBoEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cBoBoKeyword_10_0 = (Keyword)cBoEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cMbbiEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cMbbiMbbiKeyword_11_0 = (Keyword)cMbbiEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cMbboEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cMbboMbboKeyword_12_0 = (Keyword)cMbboEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cMbbiDirectEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cMbbiDirectMbbiDirectKeyword_13_0 = (Keyword)cMbbiDirectEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cMbboDirectEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cMbboDirectMbboDirectKeyword_14_0 = (Keyword)cMbboDirectEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cCalcoutEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cCalcoutCalcoutKeyword_15_0 = (Keyword)cCalcoutEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cScalcoutEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cScalcoutScalcoutKeyword_16_0 = (Keyword)cScalcoutEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cCalcEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cCalcCalcKeyword_17_0 = (Keyword)cCalcEnumLiteralDeclaration_17.eContents().get(0);
		
		//enum Recordnames:
		//	ai | ao | longin | longout | stringin | stringout | lsi |
		//	lso | waveform | bi | bo | mbbi | mbbo | mbbiDirect |
		//	mbboDirect | calcout | scalcout | calc;
		public EnumRule getRule() { return rule; }
		
		//ai | ao | longin | longout | stringin | stringout | lsi | lso | waveform | bi | bo | mbbi | mbbo | mbbiDirect |
		//mbboDirect | calcout | scalcout | calc
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ai
		public EnumLiteralDeclaration getAiEnumLiteralDeclaration_0() { return cAiEnumLiteralDeclaration_0; }
		
		//"ai"
		public Keyword getAiAiKeyword_0_0() { return cAiAiKeyword_0_0; }
		
		//ao
		public EnumLiteralDeclaration getAoEnumLiteralDeclaration_1() { return cAoEnumLiteralDeclaration_1; }
		
		//"ao"
		public Keyword getAoAoKeyword_1_0() { return cAoAoKeyword_1_0; }
		
		//longin
		public EnumLiteralDeclaration getLonginEnumLiteralDeclaration_2() { return cLonginEnumLiteralDeclaration_2; }
		
		//"longin"
		public Keyword getLonginLonginKeyword_2_0() { return cLonginLonginKeyword_2_0; }
		
		//longout
		public EnumLiteralDeclaration getLongoutEnumLiteralDeclaration_3() { return cLongoutEnumLiteralDeclaration_3; }
		
		//"longout"
		public Keyword getLongoutLongoutKeyword_3_0() { return cLongoutLongoutKeyword_3_0; }
		
		//stringin
		public EnumLiteralDeclaration getStringinEnumLiteralDeclaration_4() { return cStringinEnumLiteralDeclaration_4; }
		
		//"stringin"
		public Keyword getStringinStringinKeyword_4_0() { return cStringinStringinKeyword_4_0; }
		
		//stringout
		public EnumLiteralDeclaration getStringoutEnumLiteralDeclaration_5() { return cStringoutEnumLiteralDeclaration_5; }
		
		//"stringout"
		public Keyword getStringoutStringoutKeyword_5_0() { return cStringoutStringoutKeyword_5_0; }
		
		//lsi
		public EnumLiteralDeclaration getLsiEnumLiteralDeclaration_6() { return cLsiEnumLiteralDeclaration_6; }
		
		//"lsi"
		public Keyword getLsiLsiKeyword_6_0() { return cLsiLsiKeyword_6_0; }
		
		//lso
		public EnumLiteralDeclaration getLsoEnumLiteralDeclaration_7() { return cLsoEnumLiteralDeclaration_7; }
		
		//"lso"
		public Keyword getLsoLsoKeyword_7_0() { return cLsoLsoKeyword_7_0; }
		
		//waveform
		public EnumLiteralDeclaration getWaveformEnumLiteralDeclaration_8() { return cWaveformEnumLiteralDeclaration_8; }
		
		//"waveform"
		public Keyword getWaveformWaveformKeyword_8_0() { return cWaveformWaveformKeyword_8_0; }
		
		//bi
		public EnumLiteralDeclaration getBiEnumLiteralDeclaration_9() { return cBiEnumLiteralDeclaration_9; }
		
		//"bi"
		public Keyword getBiBiKeyword_9_0() { return cBiBiKeyword_9_0; }
		
		//bo
		public EnumLiteralDeclaration getBoEnumLiteralDeclaration_10() { return cBoEnumLiteralDeclaration_10; }
		
		//"bo"
		public Keyword getBoBoKeyword_10_0() { return cBoBoKeyword_10_0; }
		
		//mbbi
		public EnumLiteralDeclaration getMbbiEnumLiteralDeclaration_11() { return cMbbiEnumLiteralDeclaration_11; }
		
		//"mbbi"
		public Keyword getMbbiMbbiKeyword_11_0() { return cMbbiMbbiKeyword_11_0; }
		
		//mbbo
		public EnumLiteralDeclaration getMbboEnumLiteralDeclaration_12() { return cMbboEnumLiteralDeclaration_12; }
		
		//"mbbo"
		public Keyword getMbboMbboKeyword_12_0() { return cMbboMbboKeyword_12_0; }
		
		//mbbiDirect
		public EnumLiteralDeclaration getMbbiDirectEnumLiteralDeclaration_13() { return cMbbiDirectEnumLiteralDeclaration_13; }
		
		//"mbbiDirect"
		public Keyword getMbbiDirectMbbiDirectKeyword_13_0() { return cMbbiDirectMbbiDirectKeyword_13_0; }
		
		//mbboDirect
		public EnumLiteralDeclaration getMbboDirectEnumLiteralDeclaration_14() { return cMbboDirectEnumLiteralDeclaration_14; }
		
		//"mbboDirect"
		public Keyword getMbboDirectMbboDirectKeyword_14_0() { return cMbboDirectMbboDirectKeyword_14_0; }
		
		//calcout
		public EnumLiteralDeclaration getCalcoutEnumLiteralDeclaration_15() { return cCalcoutEnumLiteralDeclaration_15; }
		
		//"calcout"
		public Keyword getCalcoutCalcoutKeyword_15_0() { return cCalcoutCalcoutKeyword_15_0; }
		
		//scalcout
		public EnumLiteralDeclaration getScalcoutEnumLiteralDeclaration_16() { return cScalcoutEnumLiteralDeclaration_16; }
		
		//"scalcout"
		public Keyword getScalcoutScalcoutKeyword_16_0() { return cScalcoutScalcoutKeyword_16_0; }
		
		//calc
		public EnumLiteralDeclaration getCalcEnumLiteralDeclaration_17() { return cCalcEnumLiteralDeclaration_17; }
		
		//"calc"
		public Keyword getCalcCalcKeyword_17_0() { return cCalcCalcKeyword_17_0; }
	}
	
	private final DbModelElements pDbModel;
	private final RecordElements pRecord;
	private final FieldElements pField;
	private final InfoElements pInfo;
	private final FieldnamesElements eFieldnames;
	private final RecordnamesElements eRecordnames;
	private final TerminalRule tSL_COMMENT;
	private final DOUBLEElements pDOUBLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DbTextEditorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDbModel = new DbModelElements();
		this.pRecord = new RecordElements();
		this.pField = new FieldElements();
		this.pInfo = new InfoElements();
		this.eFieldnames = new FieldnamesElements();
		this.eRecordnames = new RecordnamesElements();
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.csstudio.xtext.dbtexteditor.DbTextEditor.SL_COMMENT");
		this.pDOUBLE = new DOUBLEElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.csstudio.xtext.dbtexteditor.DbTextEditor".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//dbModel:
	//	records+=Record*;
	public DbModelElements getDbModelAccess() {
		return pDbModel;
	}
	
	public ParserRule getDbModelRule() {
		return getDbModelAccess().getRule();
	}
	
	//Record:
	//	name='record' '(' recordname=Recordnames ',' recordLink=STRING ')' '{'
	//	infosfields+=(Info | Field)*
	//	'}';
	public RecordElements getRecordAccess() {
		return pRecord;
	}
	
	public ParserRule getRecordRule() {
		return getRecordAccess().getRule();
	}
	
	//Field:
	//	name='field' '(' fieldname=Fieldnames ',' (fieldstring=STRING | fieldint=INT | fielddouble=DOUBLE) ')';
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Info:
	//	'info' '(' name='asyn:READBACK' ',' infoValue=STRING ')';
	public InfoElements getInfoAccess() {
		return pInfo;
	}
	
	public ParserRule getInfoRule() {
		return getInfoAccess().getRule();
	}
	
	//enum Fieldnames:
	//	NAME | DESC | ASG | SCAN | PHAS | PINI | SDIS | PROC |
	//	PACT | SEVR | STAT | TIME | DTYP | ONAM | OSV | OUT |
	//	SIML | ZNAM | ZSV | INP | EGU | LINR | EGUL | EGUF |
	//	HIGH | HSV | HIHI | HHSV | EIST | EISV | EIVL | ELST |
	//	ELSV | ELVL | FRST | FRSV | FRVL | FVST | HYST | LLSV
	//	| FVSV | FVVL | MASK | NIST | NISV | NIVL | NOBT | ONST
	//	| ONSV | ONVL | SHFT | SVST | SVSV | SVVL | SXST |
	//	SXSV | SXVL | TEST | TESV | TEVL | THST | THSV | THVL
	//	| TWST | TWSV | TWVL | UNSV | ZRST | ZRSV | ZRVL
	//	| LOLO | LOW | LSV | SSCN | TSE | PREC | DRVH | LOPR
	//	| DRVL | HOPR | CALC | INPA | INPB | INPC | INPD
	//	| FLNK | INPE | INPF | INPG | INPH | INPI | INPJ
	//	| INPK | INAA | INBB | INCC | SIOL;
	public FieldnamesElements getFieldnamesAccess() {
		return eFieldnames;
	}
	
	public EnumRule getFieldnamesRule() {
		return getFieldnamesAccess().getRule();
	}
	
	//enum Recordnames:
	//	ai | ao | longin | longout | stringin | stringout | lsi |
	//	lso | waveform | bi | bo | mbbi | mbbo | mbbiDirect |
	//	mbboDirect | calcout | scalcout | calc;
	public RecordnamesElements getRecordnamesAccess() {
		return eRecordnames;
	}
	
	public EnumRule getRecordnamesRule() {
		return getRecordnamesAccess().getRule();
	}
	
	//@Override
	//terminal SL_COMMENT:
	//	'#' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//DOUBLE:
	//	INT '.' INT;
	public DOUBLEElements getDOUBLEAccess() {
		return pDOUBLE;
	}
	
	public ParserRule getDOUBLERule() {
		return getDOUBLEAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
