/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.csstudio.xtext.dbdtexteditor.dbdTextEditor.DbdTextEditorPackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class DbdTextEditorStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new DbdTextEditorRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.csstudio.org/xtext/dbdtexteditor/DbdTextEditor")) {
			EPackage.Registry.INSTANCE.put("http://www.csstudio.org/xtext/dbdtexteditor/DbdTextEditor", DbdTextEditorPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("dbd", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("dbd", serviceProvider);
	}
}
