/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.dbTextEditor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>db Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.dbModel#getRecords <em>Records</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getdbModel()
 * @model
 * @generated
 */
public interface dbModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Records</b></em>' containment reference list.
   * The list contents are of type {@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Records</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Records</em>' containment reference list.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getdbModel_Records()
   * @model containment="true"
   * @generated
   */
  EList<Record> getRecords();

} // dbModel
