/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.dbTextEditor;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Fieldnames</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getFieldnames()
 * @model
 * @generated
 */
public enum Fieldnames implements Enumerator
{
  /**
   * The '<em><b>NAME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAME_VALUE
   * @generated
   * @ordered
   */
  NAME(0, "NAME", "NAME"),

  /**
   * The '<em><b>DESC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESC_VALUE
   * @generated
   * @ordered
   */
  DESC(1, "DESC", "DESC"),

  /**
   * The '<em><b>ASG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASG_VALUE
   * @generated
   * @ordered
   */
  ASG(2, "ASG", "ASG"),

  /**
   * The '<em><b>SCAN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCAN_VALUE
   * @generated
   * @ordered
   */
  SCAN(3, "SCAN", "SCAN"),

  /**
   * The '<em><b>PHAS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PHAS_VALUE
   * @generated
   * @ordered
   */
  PHAS(4, "PHAS", "PHAS"),

  /**
   * The '<em><b>PINI</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PINI_VALUE
   * @generated
   * @ordered
   */
  PINI(5, "PINI", "PINI"),

  /**
   * The '<em><b>SDIS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SDIS_VALUE
   * @generated
   * @ordered
   */
  SDIS(6, "SDIS", "SDIS"),

  /**
   * The '<em><b>PROC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROC_VALUE
   * @generated
   * @ordered
   */
  PROC(7, "PROC", "PROC"),

  /**
   * The '<em><b>PACT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PACT_VALUE
   * @generated
   * @ordered
   */
  PACT(8, "PACT", "PACT"),

  /**
   * The '<em><b>SEVR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEVR_VALUE
   * @generated
   * @ordered
   */
  SEVR(9, "SEVR", "SEVR"),

  /**
   * The '<em><b>STAT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STAT_VALUE
   * @generated
   * @ordered
   */
  STAT(10, "STAT", "STAT"),

  /**
   * The '<em><b>TIME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TIME_VALUE
   * @generated
   * @ordered
   */
  TIME(11, "TIME", "TIME"),

  /**
   * The '<em><b>DTYP</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DTYP_VALUE
   * @generated
   * @ordered
   */
  DTYP(12, "DTYP", "DTYP"),

  /**
   * The '<em><b>ONAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONAM_VALUE
   * @generated
   * @ordered
   */
  ONAM(13, "ONAM", "ONAM"),

  /**
   * The '<em><b>OSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OSV_VALUE
   * @generated
   * @ordered
   */
  OSV(14, "OSV", "OSV"),

  /**
   * The '<em><b>OUT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OUT_VALUE
   * @generated
   * @ordered
   */
  OUT(15, "OUT", "OUT"),

  /**
   * The '<em><b>SIML</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIML_VALUE
   * @generated
   * @ordered
   */
  SIML(16, "SIML", "SIML"),

  /**
   * The '<em><b>ZNAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZNAM_VALUE
   * @generated
   * @ordered
   */
  ZNAM(17, "ZNAM", "ZNAM"),

  /**
   * The '<em><b>ZSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZSV_VALUE
   * @generated
   * @ordered
   */
  ZSV(18, "ZSV", "ZSV"),

  /**
   * The '<em><b>INP</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INP_VALUE
   * @generated
   * @ordered
   */
  INP(19, "INP", "INP"),

  /**
   * The '<em><b>EGU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EGU_VALUE
   * @generated
   * @ordered
   */
  EGU(20, "EGU", "EGU"),

  /**
   * The '<em><b>LINR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINR_VALUE
   * @generated
   * @ordered
   */
  LINR(21, "LINR", "LINR"),

  /**
   * The '<em><b>EGUL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EGUL_VALUE
   * @generated
   * @ordered
   */
  EGUL(22, "EGUL", "EGUL"),

  /**
   * The '<em><b>EGUF</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EGUF_VALUE
   * @generated
   * @ordered
   */
  EGUF(23, "EGUF", "EGUF"),

  /**
   * The '<em><b>HIGH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HIGH_VALUE
   * @generated
   * @ordered
   */
  HIGH(24, "HIGH", "HIGH"),

  /**
   * The '<em><b>HSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HSV_VALUE
   * @generated
   * @ordered
   */
  HSV(25, "HSV", "HSV"),

  /**
   * The '<em><b>HIHI</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HIHI_VALUE
   * @generated
   * @ordered
   */
  HIHI(26, "HIHI", "HIHI"),

  /**
   * The '<em><b>HHSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HHSV_VALUE
   * @generated
   * @ordered
   */
  HHSV(27, "HHSV", "HHSV"),

  /**
   * The '<em><b>EIST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EIST_VALUE
   * @generated
   * @ordered
   */
  EIST(28, "EIST", "EIST"),

  /**
   * The '<em><b>EISV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EISV_VALUE
   * @generated
   * @ordered
   */
  EISV(29, "EISV", "EISV"),

  /**
   * The '<em><b>EIVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EIVL_VALUE
   * @generated
   * @ordered
   */
  EIVL(30, "EIVL", "EIVL"),

  /**
   * The '<em><b>ELST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELST_VALUE
   * @generated
   * @ordered
   */
  ELST(31, "ELST", "ELST"),

  /**
   * The '<em><b>ELSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELSV_VALUE
   * @generated
   * @ordered
   */
  ELSV(32, "ELSV", "ELSV"),

  /**
   * The '<em><b>ELVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELVL_VALUE
   * @generated
   * @ordered
   */
  ELVL(33, "ELVL", "ELVL"),

  /**
   * The '<em><b>FRST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRST_VALUE
   * @generated
   * @ordered
   */
  FRST(34, "FRST", "FRST"),

  /**
   * The '<em><b>FRSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRSV_VALUE
   * @generated
   * @ordered
   */
  FRSV(35, "FRSV", "FRSV"),

  /**
   * The '<em><b>FRVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRVL_VALUE
   * @generated
   * @ordered
   */
  FRVL(36, "FRVL", "FRVL"),

  /**
   * The '<em><b>FVST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FVST_VALUE
   * @generated
   * @ordered
   */
  FVST(37, "FVST", "FVST"),

  /**
   * The '<em><b>HYST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HYST_VALUE
   * @generated
   * @ordered
   */
  HYST(38, "HYST", "HYST"),

  /**
   * The '<em><b>LLSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LLSV_VALUE
   * @generated
   * @ordered
   */
  LLSV(39, "LLSV", "LLSV"),

  /**
   * The '<em><b>FVSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FVSV_VALUE
   * @generated
   * @ordered
   */
  FVSV(40, "FVSV", "FVSV"),

  /**
   * The '<em><b>FVVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FVVL_VALUE
   * @generated
   * @ordered
   */
  FVVL(41, "FVVL", "FVVL"),

  /**
   * The '<em><b>MASK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MASK_VALUE
   * @generated
   * @ordered
   */
  MASK(42, "MASK", "MASK"),

  /**
   * The '<em><b>NIST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NIST_VALUE
   * @generated
   * @ordered
   */
  NIST(43, "NIST", "NIST"),

  /**
   * The '<em><b>NISV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NISV_VALUE
   * @generated
   * @ordered
   */
  NISV(44, "NISV", "NISV"),

  /**
   * The '<em><b>NIVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NIVL_VALUE
   * @generated
   * @ordered
   */
  NIVL(45, "NIVL", "NIVL"),

  /**
   * The '<em><b>NOBT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOBT_VALUE
   * @generated
   * @ordered
   */
  NOBT(46, "NOBT", "NOBT"),

  /**
   * The '<em><b>ONST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONST_VALUE
   * @generated
   * @ordered
   */
  ONST(47, "ONST", "ONST"),

  /**
   * The '<em><b>ONSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONSV_VALUE
   * @generated
   * @ordered
   */
  ONSV(48, "ONSV", "ONSV"),

  /**
   * The '<em><b>ONVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONVL_VALUE
   * @generated
   * @ordered
   */
  ONVL(49, "ONVL", "ONVL"),

  /**
   * The '<em><b>SHFT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHFT_VALUE
   * @generated
   * @ordered
   */
  SHFT(50, "SHFT", "SHFT"),

  /**
   * The '<em><b>SVST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVST_VALUE
   * @generated
   * @ordered
   */
  SVST(51, "SVST", "SVST"),

  /**
   * The '<em><b>SVSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVSV_VALUE
   * @generated
   * @ordered
   */
  SVSV(52, "SVSV", "SVSV"),

  /**
   * The '<em><b>SVVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVVL_VALUE
   * @generated
   * @ordered
   */
  SVVL(53, "SVVL", "SVVL"),

  /**
   * The '<em><b>SXST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SXST_VALUE
   * @generated
   * @ordered
   */
  SXST(54, "SXST", "SXST"),

  /**
   * The '<em><b>SXSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SXSV_VALUE
   * @generated
   * @ordered
   */
  SXSV(55, "SXSV", "SXSV"),

  /**
   * The '<em><b>SXVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SXVL_VALUE
   * @generated
   * @ordered
   */
  SXVL(56, "SXVL", "SXVL"),

  /**
   * The '<em><b>TEST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEST_VALUE
   * @generated
   * @ordered
   */
  TEST(57, "TEST", "TEST"),

  /**
   * The '<em><b>TESV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TESV_VALUE
   * @generated
   * @ordered
   */
  TESV(58, "TESV", "TESV"),

  /**
   * The '<em><b>TEVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEVL_VALUE
   * @generated
   * @ordered
   */
  TEVL(59, "TEVL", "TEVL"),

  /**
   * The '<em><b>THST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THST_VALUE
   * @generated
   * @ordered
   */
  THST(60, "THST", "THST"),

  /**
   * The '<em><b>THSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THSV_VALUE
   * @generated
   * @ordered
   */
  THSV(61, "THSV", "THSV"),

  /**
   * The '<em><b>THVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THVL_VALUE
   * @generated
   * @ordered
   */
  THVL(62, "THVL", "THVL"),

  /**
   * The '<em><b>TWST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TWST_VALUE
   * @generated
   * @ordered
   */
  TWST(63, "TWST", "TWST"),

  /**
   * The '<em><b>TWSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TWSV_VALUE
   * @generated
   * @ordered
   */
  TWSV(64, "TWSV", "TWSV"),

  /**
   * The '<em><b>TWVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TWVL_VALUE
   * @generated
   * @ordered
   */
  TWVL(65, "TWVL", "TWVL"),

  /**
   * The '<em><b>UNSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNSV_VALUE
   * @generated
   * @ordered
   */
  UNSV(66, "UNSV", "UNSV"),

  /**
   * The '<em><b>ZRST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZRST_VALUE
   * @generated
   * @ordered
   */
  ZRST(67, "ZRST", "ZRST"),

  /**
   * The '<em><b>ZRSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZRSV_VALUE
   * @generated
   * @ordered
   */
  ZRSV(68, "ZRSV", "ZRSV"),

  /**
   * The '<em><b>ZRVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZRVL_VALUE
   * @generated
   * @ordered
   */
  ZRVL(69, "ZRVL", "ZRVL"),

  /**
   * The '<em><b>LOLO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOLO_VALUE
   * @generated
   * @ordered
   */
  LOLO(70, "LOLO", "LOLO"),

  /**
   * The '<em><b>LOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOW_VALUE
   * @generated
   * @ordered
   */
  LOW(71, "LOW", "LOW"),

  /**
   * The '<em><b>LSV</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LSV_VALUE
   * @generated
   * @ordered
   */
  LSV(72, "LSV", "LSV"),

  /**
   * The '<em><b>SSCN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SSCN_VALUE
   * @generated
   * @ordered
   */
  SSCN(73, "SSCN", "SSCN"),

  /**
   * The '<em><b>TSE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TSE_VALUE
   * @generated
   * @ordered
   */
  TSE(74, "TSE", "TSE"),

  /**
   * The '<em><b>PREC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PREC_VALUE
   * @generated
   * @ordered
   */
  PREC(75, "PREC", "PREC"),

  /**
   * The '<em><b>DRVH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRVH_VALUE
   * @generated
   * @ordered
   */
  DRVH(76, "DRVH", "DRVH"),

  /**
   * The '<em><b>LOPR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOPR_VALUE
   * @generated
   * @ordered
   */
  LOPR(77, "LOPR", "LOPR"),

  /**
   * The '<em><b>DRVL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRVL_VALUE
   * @generated
   * @ordered
   */
  DRVL(78, "DRVL", "DRVL"),

  /**
   * The '<em><b>HOPR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HOPR_VALUE
   * @generated
   * @ordered
   */
  HOPR(79, "HOPR", "HOPR"),

  /**
   * The '<em><b>CALC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALC_VALUE
   * @generated
   * @ordered
   */
  CALC(80, "CALC", "CALC"),

  /**
   * The '<em><b>INPA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPA_VALUE
   * @generated
   * @ordered
   */
  INPA(81, "INPA", "INPA"),

  /**
   * The '<em><b>INPB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPB_VALUE
   * @generated
   * @ordered
   */
  INPB(82, "INPB", "INPB"),

  /**
   * The '<em><b>INPC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPC_VALUE
   * @generated
   * @ordered
   */
  INPC(83, "INPC", "INPC"),

  /**
   * The '<em><b>INPD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPD_VALUE
   * @generated
   * @ordered
   */
  INPD(84, "INPD", "INPD"),

  /**
   * The '<em><b>FLNK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLNK_VALUE
   * @generated
   * @ordered
   */
  FLNK(85, "FLNK", "FLNK"),

  /**
   * The '<em><b>INPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPE_VALUE
   * @generated
   * @ordered
   */
  INPE(86, "INPE", "INPE"),

  /**
   * The '<em><b>INPF</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPF_VALUE
   * @generated
   * @ordered
   */
  INPF(87, "INPF", "INPF"),

  /**
   * The '<em><b>INPG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPG_VALUE
   * @generated
   * @ordered
   */
  INPG(88, "INPG", "INPG"),

  /**
   * The '<em><b>INPH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPH_VALUE
   * @generated
   * @ordered
   */
  INPH(89, "INPH", "INPH"),

  /**
   * The '<em><b>INPI</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPI_VALUE
   * @generated
   * @ordered
   */
  INPI(90, "INPI", "INPI"),

  /**
   * The '<em><b>INPJ</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPJ_VALUE
   * @generated
   * @ordered
   */
  INPJ(91, "INPJ", "INPJ"),

  /**
   * The '<em><b>INPK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPK_VALUE
   * @generated
   * @ordered
   */
  INPK(92, "INPK", "INPK"),

  /**
   * The '<em><b>INAA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INAA_VALUE
   * @generated
   * @ordered
   */
  INAA(93, "INAA", "INAA"),

  /**
   * The '<em><b>INBB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INBB_VALUE
   * @generated
   * @ordered
   */
  INBB(94, "INBB", "INBB"),

  /**
   * The '<em><b>INCC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCC_VALUE
   * @generated
   * @ordered
   */
  INCC(95, "INCC", "INCC"),

  /**
   * The '<em><b>SIOL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIOL_VALUE
   * @generated
   * @ordered
   */
  SIOL(96, "SIOL", "SIOL");

  /**
   * The '<em><b>NAME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NAME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NAME
   * @model
   * @generated
   * @ordered
   */
  public static final int NAME_VALUE = 0;

  /**
   * The '<em><b>DESC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DESC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DESC
   * @model
   * @generated
   * @ordered
   */
  public static final int DESC_VALUE = 1;

  /**
   * The '<em><b>ASG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ASG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASG
   * @model
   * @generated
   * @ordered
   */
  public static final int ASG_VALUE = 2;

  /**
   * The '<em><b>SCAN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SCAN</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCAN
   * @model
   * @generated
   * @ordered
   */
  public static final int SCAN_VALUE = 3;

  /**
   * The '<em><b>PHAS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PHAS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PHAS
   * @model
   * @generated
   * @ordered
   */
  public static final int PHAS_VALUE = 4;

  /**
   * The '<em><b>PINI</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PINI</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PINI
   * @model
   * @generated
   * @ordered
   */
  public static final int PINI_VALUE = 5;

  /**
   * The '<em><b>SDIS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SDIS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SDIS
   * @model
   * @generated
   * @ordered
   */
  public static final int SDIS_VALUE = 6;

  /**
   * The '<em><b>PROC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PROC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PROC
   * @model
   * @generated
   * @ordered
   */
  public static final int PROC_VALUE = 7;

  /**
   * The '<em><b>PACT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PACT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PACT
   * @model
   * @generated
   * @ordered
   */
  public static final int PACT_VALUE = 8;

  /**
   * The '<em><b>SEVR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SEVR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SEVR
   * @model
   * @generated
   * @ordered
   */
  public static final int SEVR_VALUE = 9;

  /**
   * The '<em><b>STAT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>STAT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STAT
   * @model
   * @generated
   * @ordered
   */
  public static final int STAT_VALUE = 10;

  /**
   * The '<em><b>TIME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TIME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TIME
   * @model
   * @generated
   * @ordered
   */
  public static final int TIME_VALUE = 11;

  /**
   * The '<em><b>DTYP</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DTYP</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DTYP
   * @model
   * @generated
   * @ordered
   */
  public static final int DTYP_VALUE = 12;

  /**
   * The '<em><b>ONAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ONAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ONAM
   * @model
   * @generated
   * @ordered
   */
  public static final int ONAM_VALUE = 13;

  /**
   * The '<em><b>OSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OSV
   * @model
   * @generated
   * @ordered
   */
  public static final int OSV_VALUE = 14;

  /**
   * The '<em><b>OUT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OUT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OUT
   * @model
   * @generated
   * @ordered
   */
  public static final int OUT_VALUE = 15;

  /**
   * The '<em><b>SIML</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SIML</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SIML
   * @model
   * @generated
   * @ordered
   */
  public static final int SIML_VALUE = 16;

  /**
   * The '<em><b>ZNAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ZNAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ZNAM
   * @model
   * @generated
   * @ordered
   */
  public static final int ZNAM_VALUE = 17;

  /**
   * The '<em><b>ZSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ZSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ZSV
   * @model
   * @generated
   * @ordered
   */
  public static final int ZSV_VALUE = 18;

  /**
   * The '<em><b>INP</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INP</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INP
   * @model
   * @generated
   * @ordered
   */
  public static final int INP_VALUE = 19;

  /**
   * The '<em><b>EGU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EGU</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EGU
   * @model
   * @generated
   * @ordered
   */
  public static final int EGU_VALUE = 20;

  /**
   * The '<em><b>LINR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LINR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LINR
   * @model
   * @generated
   * @ordered
   */
  public static final int LINR_VALUE = 21;

  /**
   * The '<em><b>EGUL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EGUL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EGUL
   * @model
   * @generated
   * @ordered
   */
  public static final int EGUL_VALUE = 22;

  /**
   * The '<em><b>EGUF</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EGUF</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EGUF
   * @model
   * @generated
   * @ordered
   */
  public static final int EGUF_VALUE = 23;

  /**
   * The '<em><b>HIGH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HIGH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HIGH
   * @model
   * @generated
   * @ordered
   */
  public static final int HIGH_VALUE = 24;

  /**
   * The '<em><b>HSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HSV
   * @model
   * @generated
   * @ordered
   */
  public static final int HSV_VALUE = 25;

  /**
   * The '<em><b>HIHI</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HIHI</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HIHI
   * @model
   * @generated
   * @ordered
   */
  public static final int HIHI_VALUE = 26;

  /**
   * The '<em><b>HHSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HHSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HHSV
   * @model
   * @generated
   * @ordered
   */
  public static final int HHSV_VALUE = 27;

  /**
   * The '<em><b>EIST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EIST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EIST
   * @model
   * @generated
   * @ordered
   */
  public static final int EIST_VALUE = 28;

  /**
   * The '<em><b>EISV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EISV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EISV
   * @model
   * @generated
   * @ordered
   */
  public static final int EISV_VALUE = 29;

  /**
   * The '<em><b>EIVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EIVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EIVL
   * @model
   * @generated
   * @ordered
   */
  public static final int EIVL_VALUE = 30;

  /**
   * The '<em><b>ELST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ELST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ELST
   * @model
   * @generated
   * @ordered
   */
  public static final int ELST_VALUE = 31;

  /**
   * The '<em><b>ELSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ELSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ELSV
   * @model
   * @generated
   * @ordered
   */
  public static final int ELSV_VALUE = 32;

  /**
   * The '<em><b>ELVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ELVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ELVL
   * @model
   * @generated
   * @ordered
   */
  public static final int ELVL_VALUE = 33;

  /**
   * The '<em><b>FRST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FRST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FRST
   * @model
   * @generated
   * @ordered
   */
  public static final int FRST_VALUE = 34;

  /**
   * The '<em><b>FRSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FRSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FRSV
   * @model
   * @generated
   * @ordered
   */
  public static final int FRSV_VALUE = 35;

  /**
   * The '<em><b>FRVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FRVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FRVL
   * @model
   * @generated
   * @ordered
   */
  public static final int FRVL_VALUE = 36;

  /**
   * The '<em><b>FVST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FVST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FVST
   * @model
   * @generated
   * @ordered
   */
  public static final int FVST_VALUE = 37;

  /**
   * The '<em><b>HYST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HYST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HYST
   * @model
   * @generated
   * @ordered
   */
  public static final int HYST_VALUE = 38;

  /**
   * The '<em><b>LLSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LLSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LLSV
   * @model
   * @generated
   * @ordered
   */
  public static final int LLSV_VALUE = 39;

  /**
   * The '<em><b>FVSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FVSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FVSV
   * @model
   * @generated
   * @ordered
   */
  public static final int FVSV_VALUE = 40;

  /**
   * The '<em><b>FVVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FVVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FVVL
   * @model
   * @generated
   * @ordered
   */
  public static final int FVVL_VALUE = 41;

  /**
   * The '<em><b>MASK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MASK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MASK
   * @model
   * @generated
   * @ordered
   */
  public static final int MASK_VALUE = 42;

  /**
   * The '<em><b>NIST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NIST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NIST
   * @model
   * @generated
   * @ordered
   */
  public static final int NIST_VALUE = 43;

  /**
   * The '<em><b>NISV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NISV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NISV
   * @model
   * @generated
   * @ordered
   */
  public static final int NISV_VALUE = 44;

  /**
   * The '<em><b>NIVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NIVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NIVL
   * @model
   * @generated
   * @ordered
   */
  public static final int NIVL_VALUE = 45;

  /**
   * The '<em><b>NOBT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NOBT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NOBT
   * @model
   * @generated
   * @ordered
   */
  public static final int NOBT_VALUE = 46;

  /**
   * The '<em><b>ONST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ONST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ONST
   * @model
   * @generated
   * @ordered
   */
  public static final int ONST_VALUE = 47;

  /**
   * The '<em><b>ONSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ONSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ONSV
   * @model
   * @generated
   * @ordered
   */
  public static final int ONSV_VALUE = 48;

  /**
   * The '<em><b>ONVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ONVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ONVL
   * @model
   * @generated
   * @ordered
   */
  public static final int ONVL_VALUE = 49;

  /**
   * The '<em><b>SHFT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SHFT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SHFT
   * @model
   * @generated
   * @ordered
   */
  public static final int SHFT_VALUE = 50;

  /**
   * The '<em><b>SVST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SVST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SVST
   * @model
   * @generated
   * @ordered
   */
  public static final int SVST_VALUE = 51;

  /**
   * The '<em><b>SVSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SVSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SVSV
   * @model
   * @generated
   * @ordered
   */
  public static final int SVSV_VALUE = 52;

  /**
   * The '<em><b>SVVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SVVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SVVL
   * @model
   * @generated
   * @ordered
   */
  public static final int SVVL_VALUE = 53;

  /**
   * The '<em><b>SXST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SXST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SXST
   * @model
   * @generated
   * @ordered
   */
  public static final int SXST_VALUE = 54;

  /**
   * The '<em><b>SXSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SXSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SXSV
   * @model
   * @generated
   * @ordered
   */
  public static final int SXSV_VALUE = 55;

  /**
   * The '<em><b>SXVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SXVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SXVL
   * @model
   * @generated
   * @ordered
   */
  public static final int SXVL_VALUE = 56;

  /**
   * The '<em><b>TEST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TEST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TEST
   * @model
   * @generated
   * @ordered
   */
  public static final int TEST_VALUE = 57;

  /**
   * The '<em><b>TESV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TESV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TESV
   * @model
   * @generated
   * @ordered
   */
  public static final int TESV_VALUE = 58;

  /**
   * The '<em><b>TEVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TEVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TEVL
   * @model
   * @generated
   * @ordered
   */
  public static final int TEVL_VALUE = 59;

  /**
   * The '<em><b>THST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>THST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #THST
   * @model
   * @generated
   * @ordered
   */
  public static final int THST_VALUE = 60;

  /**
   * The '<em><b>THSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>THSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #THSV
   * @model
   * @generated
   * @ordered
   */
  public static final int THSV_VALUE = 61;

  /**
   * The '<em><b>THVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>THVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #THVL
   * @model
   * @generated
   * @ordered
   */
  public static final int THVL_VALUE = 62;

  /**
   * The '<em><b>TWST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TWST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TWST
   * @model
   * @generated
   * @ordered
   */
  public static final int TWST_VALUE = 63;

  /**
   * The '<em><b>TWSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TWSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TWSV
   * @model
   * @generated
   * @ordered
   */
  public static final int TWSV_VALUE = 64;

  /**
   * The '<em><b>TWVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TWVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TWVL
   * @model
   * @generated
   * @ordered
   */
  public static final int TWVL_VALUE = 65;

  /**
   * The '<em><b>UNSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>UNSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UNSV
   * @model
   * @generated
   * @ordered
   */
  public static final int UNSV_VALUE = 66;

  /**
   * The '<em><b>ZRST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ZRST</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ZRST
   * @model
   * @generated
   * @ordered
   */
  public static final int ZRST_VALUE = 67;

  /**
   * The '<em><b>ZRSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ZRSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ZRSV
   * @model
   * @generated
   * @ordered
   */
  public static final int ZRSV_VALUE = 68;

  /**
   * The '<em><b>ZRVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ZRVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ZRVL
   * @model
   * @generated
   * @ordered
   */
  public static final int ZRVL_VALUE = 69;

  /**
   * The '<em><b>LOLO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LOLO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LOLO
   * @model
   * @generated
   * @ordered
   */
  public static final int LOLO_VALUE = 70;

  /**
   * The '<em><b>LOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LOW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LOW
   * @model
   * @generated
   * @ordered
   */
  public static final int LOW_VALUE = 71;

  /**
   * The '<em><b>LSV</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LSV</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LSV
   * @model
   * @generated
   * @ordered
   */
  public static final int LSV_VALUE = 72;

  /**
   * The '<em><b>SSCN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SSCN</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SSCN
   * @model
   * @generated
   * @ordered
   */
  public static final int SSCN_VALUE = 73;

  /**
   * The '<em><b>TSE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TSE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TSE
   * @model
   * @generated
   * @ordered
   */
  public static final int TSE_VALUE = 74;

  /**
   * The '<em><b>PREC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PREC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PREC
   * @model
   * @generated
   * @ordered
   */
  public static final int PREC_VALUE = 75;

  /**
   * The '<em><b>DRVH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DRVH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DRVH
   * @model
   * @generated
   * @ordered
   */
  public static final int DRVH_VALUE = 76;

  /**
   * The '<em><b>LOPR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LOPR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LOPR
   * @model
   * @generated
   * @ordered
   */
  public static final int LOPR_VALUE = 77;

  /**
   * The '<em><b>DRVL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DRVL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DRVL
   * @model
   * @generated
   * @ordered
   */
  public static final int DRVL_VALUE = 78;

  /**
   * The '<em><b>HOPR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>HOPR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HOPR
   * @model
   * @generated
   * @ordered
   */
  public static final int HOPR_VALUE = 79;

  /**
   * The '<em><b>CALC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CALC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CALC
   * @model
   * @generated
   * @ordered
   */
  public static final int CALC_VALUE = 80;

  /**
   * The '<em><b>INPA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPA
   * @model
   * @generated
   * @ordered
   */
  public static final int INPA_VALUE = 81;

  /**
   * The '<em><b>INPB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPB
   * @model
   * @generated
   * @ordered
   */
  public static final int INPB_VALUE = 82;

  /**
   * The '<em><b>INPC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPC
   * @model
   * @generated
   * @ordered
   */
  public static final int INPC_VALUE = 83;

  /**
   * The '<em><b>INPD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPD
   * @model
   * @generated
   * @ordered
   */
  public static final int INPD_VALUE = 84;

  /**
   * The '<em><b>FLNK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FLNK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FLNK
   * @model
   * @generated
   * @ordered
   */
  public static final int FLNK_VALUE = 85;

  /**
   * The '<em><b>INPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPE
   * @model
   * @generated
   * @ordered
   */
  public static final int INPE_VALUE = 86;

  /**
   * The '<em><b>INPF</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPF</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPF
   * @model
   * @generated
   * @ordered
   */
  public static final int INPF_VALUE = 87;

  /**
   * The '<em><b>INPG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPG
   * @model
   * @generated
   * @ordered
   */
  public static final int INPG_VALUE = 88;

  /**
   * The '<em><b>INPH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPH
   * @model
   * @generated
   * @ordered
   */
  public static final int INPH_VALUE = 89;

  /**
   * The '<em><b>INPI</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPI</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPI
   * @model
   * @generated
   * @ordered
   */
  public static final int INPI_VALUE = 90;

  /**
   * The '<em><b>INPJ</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPJ</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPJ
   * @model
   * @generated
   * @ordered
   */
  public static final int INPJ_VALUE = 91;

  /**
   * The '<em><b>INPK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INPK</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INPK
   * @model
   * @generated
   * @ordered
   */
  public static final int INPK_VALUE = 92;

  /**
   * The '<em><b>INAA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INAA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INAA
   * @model
   * @generated
   * @ordered
   */
  public static final int INAA_VALUE = 93;

  /**
   * The '<em><b>INBB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INBB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INBB
   * @model
   * @generated
   * @ordered
   */
  public static final int INBB_VALUE = 94;

  /**
   * The '<em><b>INCC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INCC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INCC
   * @model
   * @generated
   * @ordered
   */
  public static final int INCC_VALUE = 95;

  /**
   * The '<em><b>SIOL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SIOL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SIOL
   * @model
   * @generated
   * @ordered
   */
  public static final int SIOL_VALUE = 96;

  /**
   * An array of all the '<em><b>Fieldnames</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Fieldnames[] VALUES_ARRAY =
    new Fieldnames[]
    {
      NAME,
      DESC,
      ASG,
      SCAN,
      PHAS,
      PINI,
      SDIS,
      PROC,
      PACT,
      SEVR,
      STAT,
      TIME,
      DTYP,
      ONAM,
      OSV,
      OUT,
      SIML,
      ZNAM,
      ZSV,
      INP,
      EGU,
      LINR,
      EGUL,
      EGUF,
      HIGH,
      HSV,
      HIHI,
      HHSV,
      EIST,
      EISV,
      EIVL,
      ELST,
      ELSV,
      ELVL,
      FRST,
      FRSV,
      FRVL,
      FVST,
      HYST,
      LLSV,
      FVSV,
      FVVL,
      MASK,
      NIST,
      NISV,
      NIVL,
      NOBT,
      ONST,
      ONSV,
      ONVL,
      SHFT,
      SVST,
      SVSV,
      SVVL,
      SXST,
      SXSV,
      SXVL,
      TEST,
      TESV,
      TEVL,
      THST,
      THSV,
      THVL,
      TWST,
      TWSV,
      TWVL,
      UNSV,
      ZRST,
      ZRSV,
      ZRVL,
      LOLO,
      LOW,
      LSV,
      SSCN,
      TSE,
      PREC,
      DRVH,
      LOPR,
      DRVL,
      HOPR,
      CALC,
      INPA,
      INPB,
      INPC,
      INPD,
      FLNK,
      INPE,
      INPF,
      INPG,
      INPH,
      INPI,
      INPJ,
      INPK,
      INAA,
      INBB,
      INCC,
      SIOL,
    };

  /**
   * A public read-only list of all the '<em><b>Fieldnames</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Fieldnames> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Fieldnames</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fieldnames get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Fieldnames result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fieldnames</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fieldnames getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Fieldnames result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fieldnames</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fieldnames get(int value)
  {
    switch (value)
    {
      case NAME_VALUE: return NAME;
      case DESC_VALUE: return DESC;
      case ASG_VALUE: return ASG;
      case SCAN_VALUE: return SCAN;
      case PHAS_VALUE: return PHAS;
      case PINI_VALUE: return PINI;
      case SDIS_VALUE: return SDIS;
      case PROC_VALUE: return PROC;
      case PACT_VALUE: return PACT;
      case SEVR_VALUE: return SEVR;
      case STAT_VALUE: return STAT;
      case TIME_VALUE: return TIME;
      case DTYP_VALUE: return DTYP;
      case ONAM_VALUE: return ONAM;
      case OSV_VALUE: return OSV;
      case OUT_VALUE: return OUT;
      case SIML_VALUE: return SIML;
      case ZNAM_VALUE: return ZNAM;
      case ZSV_VALUE: return ZSV;
      case INP_VALUE: return INP;
      case EGU_VALUE: return EGU;
      case LINR_VALUE: return LINR;
      case EGUL_VALUE: return EGUL;
      case EGUF_VALUE: return EGUF;
      case HIGH_VALUE: return HIGH;
      case HSV_VALUE: return HSV;
      case HIHI_VALUE: return HIHI;
      case HHSV_VALUE: return HHSV;
      case EIST_VALUE: return EIST;
      case EISV_VALUE: return EISV;
      case EIVL_VALUE: return EIVL;
      case ELST_VALUE: return ELST;
      case ELSV_VALUE: return ELSV;
      case ELVL_VALUE: return ELVL;
      case FRST_VALUE: return FRST;
      case FRSV_VALUE: return FRSV;
      case FRVL_VALUE: return FRVL;
      case FVST_VALUE: return FVST;
      case HYST_VALUE: return HYST;
      case LLSV_VALUE: return LLSV;
      case FVSV_VALUE: return FVSV;
      case FVVL_VALUE: return FVVL;
      case MASK_VALUE: return MASK;
      case NIST_VALUE: return NIST;
      case NISV_VALUE: return NISV;
      case NIVL_VALUE: return NIVL;
      case NOBT_VALUE: return NOBT;
      case ONST_VALUE: return ONST;
      case ONSV_VALUE: return ONSV;
      case ONVL_VALUE: return ONVL;
      case SHFT_VALUE: return SHFT;
      case SVST_VALUE: return SVST;
      case SVSV_VALUE: return SVSV;
      case SVVL_VALUE: return SVVL;
      case SXST_VALUE: return SXST;
      case SXSV_VALUE: return SXSV;
      case SXVL_VALUE: return SXVL;
      case TEST_VALUE: return TEST;
      case TESV_VALUE: return TESV;
      case TEVL_VALUE: return TEVL;
      case THST_VALUE: return THST;
      case THSV_VALUE: return THSV;
      case THVL_VALUE: return THVL;
      case TWST_VALUE: return TWST;
      case TWSV_VALUE: return TWSV;
      case TWVL_VALUE: return TWVL;
      case UNSV_VALUE: return UNSV;
      case ZRST_VALUE: return ZRST;
      case ZRSV_VALUE: return ZRSV;
      case ZRVL_VALUE: return ZRVL;
      case LOLO_VALUE: return LOLO;
      case LOW_VALUE: return LOW;
      case LSV_VALUE: return LSV;
      case SSCN_VALUE: return SSCN;
      case TSE_VALUE: return TSE;
      case PREC_VALUE: return PREC;
      case DRVH_VALUE: return DRVH;
      case LOPR_VALUE: return LOPR;
      case DRVL_VALUE: return DRVL;
      case HOPR_VALUE: return HOPR;
      case CALC_VALUE: return CALC;
      case INPA_VALUE: return INPA;
      case INPB_VALUE: return INPB;
      case INPC_VALUE: return INPC;
      case INPD_VALUE: return INPD;
      case FLNK_VALUE: return FLNK;
      case INPE_VALUE: return INPE;
      case INPF_VALUE: return INPF;
      case INPG_VALUE: return INPG;
      case INPH_VALUE: return INPH;
      case INPI_VALUE: return INPI;
      case INPJ_VALUE: return INPJ;
      case INPK_VALUE: return INPK;
      case INAA_VALUE: return INAA;
      case INBB_VALUE: return INBB;
      case INCC_VALUE: return INCC;
      case SIOL_VALUE: return SIOL;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Fieldnames(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Fieldnames
