/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.dbTextEditor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getName <em>Name</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldname <em>Fieldname</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldstring <em>Fieldstring</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldint <em>Fieldint</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFielddouble <em>Fielddouble</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fieldname</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Fieldnames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldname</em>' attribute.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.Fieldnames
   * @see #setFieldname(Fieldnames)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField_Fieldname()
   * @model
   * @generated
   */
  Fieldnames getFieldname();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldname <em>Fieldname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldname</em>' attribute.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.Fieldnames
   * @see #getFieldname()
   * @generated
   */
  void setFieldname(Fieldnames value);

  /**
   * Returns the value of the '<em><b>Fieldstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldstring</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldstring</em>' attribute.
   * @see #setFieldstring(String)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField_Fieldstring()
   * @model
   * @generated
   */
  String getFieldstring();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldstring <em>Fieldstring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldstring</em>' attribute.
   * @see #getFieldstring()
   * @generated
   */
  void setFieldstring(String value);

  /**
   * Returns the value of the '<em><b>Fieldint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fieldint</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fieldint</em>' attribute.
   * @see #setFieldint(int)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField_Fieldint()
   * @model
   * @generated
   */
  int getFieldint();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFieldint <em>Fieldint</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fieldint</em>' attribute.
   * @see #getFieldint()
   * @generated
   */
  void setFieldint(int value);

  /**
   * Returns the value of the '<em><b>Fielddouble</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fielddouble</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fielddouble</em>' attribute.
   * @see #setFielddouble(String)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getField_Fielddouble()
   * @model
   * @generated
   */
  String getFielddouble();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Field#getFielddouble <em>Fielddouble</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fielddouble</em>' attribute.
   * @see #getFielddouble()
   * @generated
   */
  void setFielddouble(String value);

} // Field
