/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.dbTextEditor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Record</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getName <em>Name</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getRecordname <em>Recordname</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getRecordLink <em>Record Link</em>}</li>
 *   <li>{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getInfosfields <em>Infosfields</em>}</li>
 * </ul>
 *
 * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getRecord()
 * @model
 * @generated
 */
public interface Record extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getRecord_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Recordname</b></em>' attribute.
   * The literals are from the enumeration {@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Recordnames}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recordname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recordname</em>' attribute.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.Recordnames
   * @see #setRecordname(Recordnames)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getRecord_Recordname()
   * @model
   * @generated
   */
  Recordnames getRecordname();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getRecordname <em>Recordname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recordname</em>' attribute.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.Recordnames
   * @see #getRecordname()
   * @generated
   */
  void setRecordname(Recordnames value);

  /**
   * Returns the value of the '<em><b>Record Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record Link</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Link</em>' attribute.
   * @see #setRecordLink(String)
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getRecord_RecordLink()
   * @model
   * @generated
   */
  String getRecordLink();

  /**
   * Sets the value of the '{@link org.csstudio.xtext.dbtexteditor.dbTextEditor.Record#getRecordLink <em>Record Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record Link</em>' attribute.
   * @see #getRecordLink()
   * @generated
   */
  void setRecordLink(String value);

  /**
   * Returns the value of the '<em><b>Infosfields</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Infosfields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infosfields</em>' containment reference list.
   * @see org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage#getRecord_Infosfields()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getInfosfields();

} // Record
