/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.csstudio.xtext.dbdtexteditor.DbdTextEditorRuntimeModule;
import org.csstudio.xtext.dbdtexteditor.DbdTextEditorStandaloneSetup;
import org.csstudio.xtext.dbdtexteditor.ide.DbdTextEditorIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DbdTextEditorIdeSetup extends DbdTextEditorStandaloneSetup {
  @Override
  public Injector createInjector() {
    DbdTextEditorRuntimeModule _dbdTextEditorRuntimeModule = new DbdTextEditorRuntimeModule();
    DbdTextEditorIdeModule _dbdTextEditorIdeModule = new DbdTextEditorIdeModule();
    return Guice.createInjector(Modules2.mixin(_dbdTextEditorRuntimeModule, _dbdTextEditorIdeModule));
  }
}
