/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ide;

import org.csstudio.xtext.dbdtexteditor.ide.AbstractDbdTextEditorIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DbdTextEditorIdeModule extends AbstractDbdTextEditorIdeModule {
}
