/**
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbdtexteditor.ui.contentassist;

import org.csstudio.xtext.dbdtexteditor.ui.contentassist.AbstractDbdTextEditorProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DbdTextEditorProposalProvider extends AbstractDbdTextEditorProposalProvider {
}
