/*
 * generated by Xtext 2.15.0
 */
package org.csstudio.xtext.dbtexteditor.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDbTextEditorValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.csstudio.xtext.dbtexteditor.dbTextEditor.DbTextEditorPackage.eINSTANCE);
		return result;
	}
}
